// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// ArticleResponse defines model for ArticleResponse.
type ArticleResponse = Article

// ArticlesResponse defines model for ArticlesResponse.
type ArticlesResponse = ArticleListResponse

// CreateArticleRequest defines model for CreateArticleRequest.
type CreateArticleRequest = ArticleCreateRequest

// CreatePromptRequest defines model for CreatePromptRequest.
type CreatePromptRequest = PromptCreateRequest

// CreateTranscriptionRequest defines model for CreateTranscriptionRequest.
type CreateTranscriptionRequest = TranscriptionCreateRequest

// GenerateArticleRequest defines model for GenerateArticleRequest.
type GenerateArticleRequest = ArticleGenerateRequest

// GeneratedArticleResponse defines model for GeneratedArticleResponse.
type GeneratedArticleResponse = GeneratedArticle

// HealthResponse defines model for HealthResponse.
type HealthResponse = Health

// PromptResponse defines model for PromptResponse.
type PromptResponse = Prompt

// PromptsResponse defines model for PromptsResponse.
type PromptsResponse = PromptListResponse

// TranscriptionResponse defines model for TranscriptionResponse.
type TranscriptionResponse = Transcription

// UpdateArticleRequest defines model for UpdateArticleRequest.
type UpdateArticleRequest = ArticleUpdateRequest

// UpdatePromptRequest defines model for UpdatePromptRequest.
type UpdatePromptRequest = PromptUpdateRequest

// UserResponse defines model for UserResponse.
type UserResponse = User

// Article defines model for article.
type Article struct {
	Content   string     `json:"content"`
	CreatedAt time.Time  `json:"created_at"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	Id        int64      `json:"id"`
	Title     string     `json:"title"`
	UpdatedAt time.Time  `json:"updated_at"`
	UserId    int64      `json:"user_id"`
}

// ArticleCreateRequest defines model for article_create_request.
type ArticleCreateRequest struct {
	Content string `json:"content"`
	Title   string `json:"title"`
}

// ArticleGenerateRequest defines model for article_generate_request.
type ArticleGenerateRequest struct {
	PromptId        int64 `json:"prompt_id"`
	TranscriptionId int64 `json:"transcription_id"`
}

// ArticleListResponse defines model for article_list_response.
type ArticleListResponse = []Article

// ArticleUpdateRequest defines model for article_update_request.
type ArticleUpdateRequest struct {
	Content *string `json:"content,omitempty"`
	Title   *string `json:"title,omitempty"`
}

// GeneratedArticle defines model for generated_article.
type GeneratedArticle struct {
	Content string `json:"content"`
	Title   string `json:"title"`
}

// Health defines model for health.
type Health struct {
	Status string `json:"status"`
}

// Prompt defines model for prompt.
type Prompt struct {
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
	Id        int64     `json:"id"`
	IsActive  bool      `json:"is_active"`
	IsDefault bool      `json:"is_default"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
	UserId    *int64    `json:"user_id,omitempty"`
}

// PromptCreateRequest defines model for prompt_create_request.
type PromptCreateRequest struct {
	Body     string `json:"body"`
	IsActive *bool  `json:"is_active,omitempty"`
	Name     string `json:"name"`
}

// PromptListResponse defines model for prompt_list_response.
type PromptListResponse = []Prompt

// PromptUpdateRequest defines model for prompt_update_request.
type PromptUpdateRequest struct {
	Body     *string `json:"body,omitempty"`
	IsActive *bool   `json:"is_active,omitempty"`
	Name     *string `json:"name,omitempty"`
}

// Transcription defines model for transcription.
type Transcription struct {
	CreatedAt    time.Time                `json:"created_at"`
	FullText     string                   `json:"full_text"`
	Id           int64                    `json:"id"`
	SegmentsJson []map[string]interface{} `json:"segments_json"`
	UpdatedAt    time.Time                `json:"updated_at"`
	UserId       int64                    `json:"user_id"`
}

// TranscriptionCreateRequest defines model for transcription_create_request.
type TranscriptionCreateRequest struct {
	FullText     string                   `json:"full_text"`
	SegmentsJson []map[string]interface{} `json:"segments_json"`
}

// User defines model for user.
type User struct {
	AuthProvider string  `json:"auth_provider"`
	Email        *string `json:"email,omitempty"`
	Id           int64   `json:"id"`
	Name         *string `json:"name,omitempty"`
}

// CreateArticleJSONRequestBody defines body for CreateArticle for application/json ContentType.
type CreateArticleJSONRequestBody = ArticleCreateRequest

// GenerateArticleJSONRequestBody defines body for GenerateArticle for application/json ContentType.
type GenerateArticleJSONRequestBody = ArticleGenerateRequest

// UpdateArticleJSONRequestBody defines body for UpdateArticle for application/json ContentType.
type UpdateArticleJSONRequestBody = ArticleUpdateRequest

// CreatePromptJSONRequestBody defines body for CreatePrompt for application/json ContentType.
type CreatePromptJSONRequestBody = PromptCreateRequest

// UpdatePromptJSONRequestBody defines body for UpdatePrompt for application/json ContentType.
type UpdatePromptJSONRequestBody = PromptUpdateRequest

// CreateTranscriptionJSONRequestBody defines body for CreateTranscription for application/json ContentType.
type CreateTranscriptionJSONRequestBody = TranscriptionCreateRequest
