openapi: 3.0.3
info:
  title: Voiceblog API
  version: 0.1.0
paths:
  /health:
    $ref: ./paths/health.yaml
  /me:
    $ref: ./paths/me.yaml
  /prompts:
    $ref: ./paths/prompts.yaml
  /prompts/{id}:
    $ref: ./paths/prompt_by_id.yaml
  /transcriptions:
    $ref: ./paths/transcriptions.yaml
  /transcriptions/{id}:
    $ref: ./paths/transcription_by_id.yaml
components:
  schemas:
    HealthResponse:
      $ref: ./components/schemas/health.yaml
    Prompt:
      $ref: ./components/schemas/prompt.yaml
    PromptCreateRequest:
      $ref: ./components/schemas/prompt_create_request.yaml
    PromptUpdateRequest:
      $ref: ./components/schemas/prompt_update_request.yaml
    Transcription:
      $ref: ./components/schemas/transcription.yaml
    TranscriptionCreateRequest:
      $ref: ./components/schemas/transcription_create_request.yaml
    User:
      $ref: ./components/schemas/user.yaml
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
