openapi: 3.0.3
info:
  title: Voiceblog API
  version: 0.1.0
paths:
  /health:
    $ref: ./paths/health.yaml
  /me:
    $ref: ./paths/me.yaml
components:
  schemas:
    HealthResponse:
      $ref: ./components/schemas/health.yaml
    User:
      $ref: ./components/schemas/user.yaml
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
