// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Article is an object representing the database table.
type Article struct {
	ID             int64               `db:"id,pk" `
	UserID         int64               `db:"user_id" `
	PromptRunJobID null.Val[int64]     `db:"prompt_run_job_id" `
	Title          string              `db:"title" `
	Content        string              `db:"content" `
	DeletedAt      null.Val[time.Time] `db:"deleted_at" `
	CreatedAt      time.Time           `db:"created_at" `
	UpdatedAt      time.Time           `db:"updated_at" `

	R articleR `db:"-" `
}

// ArticleSlice is an alias for a slice of pointers to Article.
// This should almost always be used instead of []*Article.
type ArticleSlice []*Article

// Articles contains methods to work with the articles table
var Articles = psql.NewTablex[*Article, ArticleSlice, *ArticleSetter]("", "articles", buildArticleColumns("articles"))

// ArticlesQuery is a query on the articles table
type ArticlesQuery = *psql.ViewQuery[*Article, ArticleSlice]

// articleR is where relationships are stored.
type articleR struct {
	PromptRunJob *PromptRunJob // articles.articles_prompt_run_job_id_fkey
	User         *User         // articles.articles_user_id_fkey
}

func buildArticleColumns(alias string) articleColumns {
	return articleColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "prompt_run_job_id", "title", "content", "deleted_at", "created_at", "updated_at",
		).WithParent("articles"),
		tableAlias:     alias,
		ID:             psql.Quote(alias, "id"),
		UserID:         psql.Quote(alias, "user_id"),
		PromptRunJobID: psql.Quote(alias, "prompt_run_job_id"),
		Title:          psql.Quote(alias, "title"),
		Content:        psql.Quote(alias, "content"),
		DeletedAt:      psql.Quote(alias, "deleted_at"),
		CreatedAt:      psql.Quote(alias, "created_at"),
		UpdatedAt:      psql.Quote(alias, "updated_at"),
	}
}

type articleColumns struct {
	expr.ColumnsExpr
	tableAlias     string
	ID             psql.Expression
	UserID         psql.Expression
	PromptRunJobID psql.Expression
	Title          psql.Expression
	Content        psql.Expression
	DeletedAt      psql.Expression
	CreatedAt      psql.Expression
	UpdatedAt      psql.Expression
}

func (c articleColumns) Alias() string {
	return c.tableAlias
}

func (articleColumns) AliasedAs(alias string) articleColumns {
	return buildArticleColumns(alias)
}

// ArticleSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ArticleSetter struct {
	ID             omit.Val[int64]         `db:"id,pk" `
	UserID         omit.Val[int64]         `db:"user_id" `
	PromptRunJobID omitnull.Val[int64]     `db:"prompt_run_job_id" `
	Title          omit.Val[string]        `db:"title" `
	Content        omit.Val[string]        `db:"content" `
	DeletedAt      omitnull.Val[time.Time] `db:"deleted_at" `
	CreatedAt      omit.Val[time.Time]     `db:"created_at" `
	UpdatedAt      omit.Val[time.Time]     `db:"updated_at" `
}

func (s ArticleSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if !s.PromptRunJobID.IsUnset() {
		vals = append(vals, "prompt_run_job_id")
	}
	if s.Title.IsValue() {
		vals = append(vals, "title")
	}
	if s.Content.IsValue() {
		vals = append(vals, "content")
	}
	if !s.DeletedAt.IsUnset() {
		vals = append(vals, "deleted_at")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s ArticleSetter) Overwrite(t *Article) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if !s.PromptRunJobID.IsUnset() {
		t.PromptRunJobID = s.PromptRunJobID.MustGetNull()
	}
	if s.Title.IsValue() {
		t.Title = s.Title.MustGet()
	}
	if s.Content.IsValue() {
		t.Content = s.Content.MustGet()
	}
	if !s.DeletedAt.IsUnset() {
		t.DeletedAt = s.DeletedAt.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *ArticleSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Articles.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 8)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[1] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if !s.PromptRunJobID.IsUnset() {
			vals[2] = psql.Arg(s.PromptRunJobID.MustGetNull())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Title.IsValue() {
			vals[3] = psql.Arg(s.Title.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.Content.IsValue() {
			vals[4] = psql.Arg(s.Content.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.DeletedAt.IsUnset() {
			vals[5] = psql.Arg(s.DeletedAt.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[6] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[7] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s ArticleSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ArticleSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if !s.PromptRunJobID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "prompt_run_job_id")...),
			psql.Arg(s.PromptRunJobID),
		}})
	}

	if s.Title.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "title")...),
			psql.Arg(s.Title),
		}})
	}

	if s.Content.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "content")...),
			psql.Arg(s.Content),
		}})
	}

	if !s.DeletedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "deleted_at")...),
			psql.Arg(s.DeletedAt),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindArticle retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindArticle(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Article, error) {
	if len(cols) == 0 {
		return Articles.Query(
			sm.Where(Articles.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Articles.Query(
		sm.Where(Articles.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Articles.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ArticleExists checks the presence of a single record by primary key
func ArticleExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Articles.Query(
		sm.Where(Articles.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Article is retrieved from the database
func (o *Article) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Articles.AfterSelectHooks.RunHooks(ctx, exec, ArticleSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Articles.AfterInsertHooks.RunHooks(ctx, exec, ArticleSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Articles.AfterUpdateHooks.RunHooks(ctx, exec, ArticleSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Articles.AfterDeleteHooks.RunHooks(ctx, exec, ArticleSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Article
func (o *Article) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Article) pkEQ() dialect.Expression {
	return psql.Quote("articles", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Article
func (o *Article) Update(ctx context.Context, exec bob.Executor, s *ArticleSetter) error {
	v, err := Articles.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Article record with an executor
func (o *Article) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Articles.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Article using the executor
func (o *Article) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Articles.Query(
		sm.Where(Articles.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ArticleSlice is retrieved from the database
func (o ArticleSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Articles.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Articles.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Articles.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Articles.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ArticleSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("articles", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ArticleSlice) copyMatchingRows(from ...*Article) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ArticleSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Articles.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Article:
				o.copyMatchingRows(retrieved)
			case []*Article:
				o.copyMatchingRows(retrieved...)
			case ArticleSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Article or a slice of Article
				// then run the AfterUpdateHooks on the slice
				_, err = Articles.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ArticleSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Articles.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Article:
				o.copyMatchingRows(retrieved)
			case []*Article:
				o.copyMatchingRows(retrieved...)
			case ArticleSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Article or a slice of Article
				// then run the AfterDeleteHooks on the slice
				_, err = Articles.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ArticleSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ArticleSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Articles.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ArticleSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Articles.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ArticleSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Articles.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// PromptRunJob starts a query for related objects on prompt_run_jobs
func (o *Article) PromptRunJob(mods ...bob.Mod[*dialect.SelectQuery]) PromptRunJobsQuery {
	return PromptRunJobs.Query(append(mods,
		sm.Where(PromptRunJobs.Columns.ID.EQ(psql.Arg(o.PromptRunJobID))),
	)...)
}

func (os ArticleSlice) PromptRunJob(mods ...bob.Mod[*dialect.SelectQuery]) PromptRunJobsQuery {
	pkPromptRunJobID := make(pgtypes.Array[null.Val[int64]], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkPromptRunJobID = append(pkPromptRunJobID, o.PromptRunJobID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkPromptRunJobID), "bigint[]")),
	))

	return PromptRunJobs.Query(append(mods,
		sm.Where(psql.Group(PromptRunJobs.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// User starts a query for related objects on users
func (o *Article) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os ArticleSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "bigint[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachArticlePromptRunJob0(ctx context.Context, exec bob.Executor, count int, article0 *Article, promptRunJob1 *PromptRunJob) (*Article, error) {
	setter := &ArticleSetter{
		PromptRunJobID: omitnull.From(promptRunJob1.ID),
	}

	err := article0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachArticlePromptRunJob0: %w", err)
	}

	return article0, nil
}

func (article0 *Article) InsertPromptRunJob(ctx context.Context, exec bob.Executor, related *PromptRunJobSetter) error {
	var err error

	promptRunJob1, err := PromptRunJobs.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachArticlePromptRunJob0(ctx, exec, 1, article0, promptRunJob1)
	if err != nil {
		return err
	}

	article0.R.PromptRunJob = promptRunJob1

	promptRunJob1.R.Article = article0

	return nil
}

func (article0 *Article) AttachPromptRunJob(ctx context.Context, exec bob.Executor, promptRunJob1 *PromptRunJob) error {
	var err error

	_, err = attachArticlePromptRunJob0(ctx, exec, 1, article0, promptRunJob1)
	if err != nil {
		return err
	}

	article0.R.PromptRunJob = promptRunJob1

	promptRunJob1.R.Article = article0

	return nil
}

func attachArticleUser0(ctx context.Context, exec bob.Executor, count int, article0 *Article, user1 *User) (*Article, error) {
	setter := &ArticleSetter{
		UserID: omit.From(user1.ID),
	}

	err := article0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachArticleUser0: %w", err)
	}

	return article0, nil
}

func (article0 *Article) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachArticleUser0(ctx, exec, 1, article0, user1)
	if err != nil {
		return err
	}

	article0.R.User = user1

	user1.R.Articles = append(user1.R.Articles, article0)

	return nil
}

func (article0 *Article) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachArticleUser0(ctx, exec, 1, article0, user1)
	if err != nil {
		return err
	}

	article0.R.User = user1

	user1.R.Articles = append(user1.R.Articles, article0)

	return nil
}

type articleWhere[Q psql.Filterable] struct {
	ID             psql.WhereMod[Q, int64]
	UserID         psql.WhereMod[Q, int64]
	PromptRunJobID psql.WhereNullMod[Q, int64]
	Title          psql.WhereMod[Q, string]
	Content        psql.WhereMod[Q, string]
	DeletedAt      psql.WhereNullMod[Q, time.Time]
	CreatedAt      psql.WhereMod[Q, time.Time]
	UpdatedAt      psql.WhereMod[Q, time.Time]
}

func (articleWhere[Q]) AliasedAs(alias string) articleWhere[Q] {
	return buildArticleWhere[Q](buildArticleColumns(alias))
}

func buildArticleWhere[Q psql.Filterable](cols articleColumns) articleWhere[Q] {
	return articleWhere[Q]{
		ID:             psql.Where[Q, int64](cols.ID),
		UserID:         psql.Where[Q, int64](cols.UserID),
		PromptRunJobID: psql.WhereNull[Q, int64](cols.PromptRunJobID),
		Title:          psql.Where[Q, string](cols.Title),
		Content:        psql.Where[Q, string](cols.Content),
		DeletedAt:      psql.WhereNull[Q, time.Time](cols.DeletedAt),
		CreatedAt:      psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:      psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Article) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "PromptRunJob":
		rel, ok := retrieved.(*PromptRunJob)
		if !ok {
			return fmt.Errorf("article cannot load %T as %q", retrieved, name)
		}

		o.R.PromptRunJob = rel

		if rel != nil {
			rel.R.Article = o
		}
		return nil
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("article cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.Articles = ArticleSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("article has no relationship %q", name)
	}
}

type articlePreloader struct {
	PromptRunJob func(...psql.PreloadOption) psql.Preloader
	User         func(...psql.PreloadOption) psql.Preloader
}

func buildArticlePreloader() articlePreloader {
	return articlePreloader{
		PromptRunJob: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*PromptRunJob, PromptRunJobSlice](psql.PreloadRel{
				Name: "PromptRunJob",
				Sides: []psql.PreloadSide{
					{
						From:        Articles,
						To:          PromptRunJobs,
						FromColumns: []string{"prompt_run_job_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, PromptRunJobs.Columns.Names(), opts...)
		},
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        Articles,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type articleThenLoader[Q orm.Loadable] struct {
	PromptRunJob func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	User         func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildArticleThenLoader[Q orm.Loadable]() articleThenLoader[Q] {
	type PromptRunJobLoadInterface interface {
		LoadPromptRunJob(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return articleThenLoader[Q]{
		PromptRunJob: thenLoadBuilder[Q](
			"PromptRunJob",
			func(ctx context.Context, exec bob.Executor, retrieved PromptRunJobLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadPromptRunJob(ctx, exec, mods...)
			},
		),
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadPromptRunJob loads the article's PromptRunJob into the .R struct
func (o *Article) LoadPromptRunJob(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.PromptRunJob = nil

	related, err := o.PromptRunJob(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Article = o

	o.R.PromptRunJob = related
	return nil
}

// LoadPromptRunJob loads the article's PromptRunJob into the .R struct
func (os ArticleSlice) LoadPromptRunJob(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	promptRunJobs, err := os.PromptRunJob(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range promptRunJobs {
			if !o.PromptRunJobID.IsValue() {
				continue
			}

			if !(o.PromptRunJobID.IsValue() && o.PromptRunJobID.MustGet() == rel.ID) {
				continue
			}

			rel.R.Article = o

			o.R.PromptRunJob = rel
			break
		}
	}

	return nil
}

// LoadUser loads the article's User into the .R struct
func (o *Article) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Articles = ArticleSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the article's User into the .R struct
func (os ArticleSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.Articles = append(rel.R.Articles, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type articleJoins[Q dialect.Joinable] struct {
	typ          string
	PromptRunJob modAs[Q, promptRunJobColumns]
	User         modAs[Q, userColumns]
}

func (j articleJoins[Q]) aliasedAs(alias string) articleJoins[Q] {
	return buildArticleJoins[Q](buildArticleColumns(alias), j.typ)
}

func buildArticleJoins[Q dialect.Joinable](cols articleColumns, typ string) articleJoins[Q] {
	return articleJoins[Q]{
		typ: typ,
		PromptRunJob: modAs[Q, promptRunJobColumns]{
			c: PromptRunJobs.Columns,
			f: func(to promptRunJobColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, PromptRunJobs.Name().As(to.Alias())).On(
						to.ID.EQ(cols.PromptRunJobID),
					))
				}

				return mods
			},
		},
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
