// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// ArticleShareTarget is an object representing the database table.
type ArticleShareTarget struct {
	ID          int64               `db:"id,pk" `
	ArticleID   int64               `db:"article_id" `
	Provider    string              `db:"provider" `
	ExternalID  string              `db:"external_id" `
	ExternalURL string              `db:"external_url" `
	PublishedAt null.Val[time.Time] `db:"published_at" `
	CreatedAt   time.Time           `db:"created_at" `
	UpdatedAt   time.Time           `db:"updated_at" `

	R articleShareTargetR `db:"-" `
}

// ArticleShareTargetSlice is an alias for a slice of pointers to ArticleShareTarget.
// This should almost always be used instead of []*ArticleShareTarget.
type ArticleShareTargetSlice []*ArticleShareTarget

// ArticleShareTargets contains methods to work with the article_share_targets table
var ArticleShareTargets = psql.NewTablex[*ArticleShareTarget, ArticleShareTargetSlice, *ArticleShareTargetSetter]("", "article_share_targets", buildArticleShareTargetColumns("article_share_targets"))

// ArticleShareTargetsQuery is a query on the article_share_targets table
type ArticleShareTargetsQuery = *psql.ViewQuery[*ArticleShareTarget, ArticleShareTargetSlice]

// articleShareTargetR is where relationships are stored.
type articleShareTargetR struct {
	Article *Article // article_share_targets.article_share_targets_article_id_fkey
}

func buildArticleShareTargetColumns(alias string) articleShareTargetColumns {
	return articleShareTargetColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "article_id", "provider", "external_id", "external_url", "published_at", "created_at", "updated_at",
		).WithParent("article_share_targets"),
		tableAlias:  alias,
		ID:          psql.Quote(alias, "id"),
		ArticleID:   psql.Quote(alias, "article_id"),
		Provider:    psql.Quote(alias, "provider"),
		ExternalID:  psql.Quote(alias, "external_id"),
		ExternalURL: psql.Quote(alias, "external_url"),
		PublishedAt: psql.Quote(alias, "published_at"),
		CreatedAt:   psql.Quote(alias, "created_at"),
		UpdatedAt:   psql.Quote(alias, "updated_at"),
	}
}

type articleShareTargetColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          psql.Expression
	ArticleID   psql.Expression
	Provider    psql.Expression
	ExternalID  psql.Expression
	ExternalURL psql.Expression
	PublishedAt psql.Expression
	CreatedAt   psql.Expression
	UpdatedAt   psql.Expression
}

func (c articleShareTargetColumns) Alias() string {
	return c.tableAlias
}

func (articleShareTargetColumns) AliasedAs(alias string) articleShareTargetColumns {
	return buildArticleShareTargetColumns(alias)
}

// ArticleShareTargetSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ArticleShareTargetSetter struct {
	ID          omit.Val[int64]         `db:"id,pk" `
	ArticleID   omit.Val[int64]         `db:"article_id" `
	Provider    omit.Val[string]        `db:"provider" `
	ExternalID  omit.Val[string]        `db:"external_id" `
	ExternalURL omit.Val[string]        `db:"external_url" `
	PublishedAt omitnull.Val[time.Time] `db:"published_at" `
	CreatedAt   omit.Val[time.Time]     `db:"created_at" `
	UpdatedAt   omit.Val[time.Time]     `db:"updated_at" `
}

func (s ArticleShareTargetSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.ArticleID.IsValue() {
		vals = append(vals, "article_id")
	}
	if s.Provider.IsValue() {
		vals = append(vals, "provider")
	}
	if s.ExternalID.IsValue() {
		vals = append(vals, "external_id")
	}
	if s.ExternalURL.IsValue() {
		vals = append(vals, "external_url")
	}
	if !s.PublishedAt.IsUnset() {
		vals = append(vals, "published_at")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s ArticleShareTargetSetter) Overwrite(t *ArticleShareTarget) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.ArticleID.IsValue() {
		t.ArticleID = s.ArticleID.MustGet()
	}
	if s.Provider.IsValue() {
		t.Provider = s.Provider.MustGet()
	}
	if s.ExternalID.IsValue() {
		t.ExternalID = s.ExternalID.MustGet()
	}
	if s.ExternalURL.IsValue() {
		t.ExternalURL = s.ExternalURL.MustGet()
	}
	if !s.PublishedAt.IsUnset() {
		t.PublishedAt = s.PublishedAt.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *ArticleShareTargetSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return ArticleShareTargets.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 8)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.ArticleID.IsValue() {
			vals[1] = psql.Arg(s.ArticleID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Provider.IsValue() {
			vals[2] = psql.Arg(s.Provider.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.ExternalID.IsValue() {
			vals[3] = psql.Arg(s.ExternalID.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.ExternalURL.IsValue() {
			vals[4] = psql.Arg(s.ExternalURL.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.PublishedAt.IsUnset() {
			vals[5] = psql.Arg(s.PublishedAt.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[6] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[7] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s ArticleShareTargetSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ArticleShareTargetSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.ArticleID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "article_id")...),
			psql.Arg(s.ArticleID),
		}})
	}

	if s.Provider.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "provider")...),
			psql.Arg(s.Provider),
		}})
	}

	if s.ExternalID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "external_id")...),
			psql.Arg(s.ExternalID),
		}})
	}

	if s.ExternalURL.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "external_url")...),
			psql.Arg(s.ExternalURL),
		}})
	}

	if !s.PublishedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "published_at")...),
			psql.Arg(s.PublishedAt),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindArticleShareTarget retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindArticleShareTarget(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*ArticleShareTarget, error) {
	if len(cols) == 0 {
		return ArticleShareTargets.Query(
			sm.Where(ArticleShareTargets.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return ArticleShareTargets.Query(
		sm.Where(ArticleShareTargets.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(ArticleShareTargets.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ArticleShareTargetExists checks the presence of a single record by primary key
func ArticleShareTargetExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return ArticleShareTargets.Query(
		sm.Where(ArticleShareTargets.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after ArticleShareTarget is retrieved from the database
func (o *ArticleShareTarget) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ArticleShareTargets.AfterSelectHooks.RunHooks(ctx, exec, ArticleShareTargetSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = ArticleShareTargets.AfterInsertHooks.RunHooks(ctx, exec, ArticleShareTargetSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = ArticleShareTargets.AfterUpdateHooks.RunHooks(ctx, exec, ArticleShareTargetSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = ArticleShareTargets.AfterDeleteHooks.RunHooks(ctx, exec, ArticleShareTargetSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the ArticleShareTarget
func (o *ArticleShareTarget) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *ArticleShareTarget) pkEQ() dialect.Expression {
	return psql.Quote("article_share_targets", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the ArticleShareTarget
func (o *ArticleShareTarget) Update(ctx context.Context, exec bob.Executor, s *ArticleShareTargetSetter) error {
	v, err := ArticleShareTargets.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single ArticleShareTarget record with an executor
func (o *ArticleShareTarget) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := ArticleShareTargets.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the ArticleShareTarget using the executor
func (o *ArticleShareTarget) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := ArticleShareTargets.Query(
		sm.Where(ArticleShareTargets.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ArticleShareTargetSlice is retrieved from the database
func (o ArticleShareTargetSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ArticleShareTargets.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = ArticleShareTargets.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = ArticleShareTargets.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = ArticleShareTargets.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ArticleShareTargetSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("article_share_targets", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ArticleShareTargetSlice) copyMatchingRows(from ...*ArticleShareTarget) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ArticleShareTargetSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ArticleShareTargets.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ArticleShareTarget:
				o.copyMatchingRows(retrieved)
			case []*ArticleShareTarget:
				o.copyMatchingRows(retrieved...)
			case ArticleShareTargetSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ArticleShareTarget or a slice of ArticleShareTarget
				// then run the AfterUpdateHooks on the slice
				_, err = ArticleShareTargets.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ArticleShareTargetSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ArticleShareTargets.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ArticleShareTarget:
				o.copyMatchingRows(retrieved)
			case []*ArticleShareTarget:
				o.copyMatchingRows(retrieved...)
			case ArticleShareTargetSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ArticleShareTarget or a slice of ArticleShareTarget
				// then run the AfterDeleteHooks on the slice
				_, err = ArticleShareTargets.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ArticleShareTargetSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ArticleShareTargetSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ArticleShareTargets.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ArticleShareTargetSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ArticleShareTargets.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ArticleShareTargetSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := ArticleShareTargets.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Article starts a query for related objects on articles
func (o *ArticleShareTarget) Article(mods ...bob.Mod[*dialect.SelectQuery]) ArticlesQuery {
	return Articles.Query(append(mods,
		sm.Where(Articles.Columns.ID.EQ(psql.Arg(o.ArticleID))),
	)...)
}

func (os ArticleShareTargetSlice) Article(mods ...bob.Mod[*dialect.SelectQuery]) ArticlesQuery {
	pkArticleID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkArticleID = append(pkArticleID, o.ArticleID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkArticleID), "bigint[]")),
	))

	return Articles.Query(append(mods,
		sm.Where(psql.Group(Articles.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachArticleShareTargetArticle0(ctx context.Context, exec bob.Executor, count int, articleShareTarget0 *ArticleShareTarget, article1 *Article) (*ArticleShareTarget, error) {
	setter := &ArticleShareTargetSetter{
		ArticleID: omit.From(article1.ID),
	}

	err := articleShareTarget0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachArticleShareTargetArticle0: %w", err)
	}

	return articleShareTarget0, nil
}

func (articleShareTarget0 *ArticleShareTarget) InsertArticle(ctx context.Context, exec bob.Executor, related *ArticleSetter) error {
	var err error

	article1, err := Articles.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachArticleShareTargetArticle0(ctx, exec, 1, articleShareTarget0, article1)
	if err != nil {
		return err
	}

	articleShareTarget0.R.Article = article1

	article1.R.ArticleShareTargets = append(article1.R.ArticleShareTargets, articleShareTarget0)

	return nil
}

func (articleShareTarget0 *ArticleShareTarget) AttachArticle(ctx context.Context, exec bob.Executor, article1 *Article) error {
	var err error

	_, err = attachArticleShareTargetArticle0(ctx, exec, 1, articleShareTarget0, article1)
	if err != nil {
		return err
	}

	articleShareTarget0.R.Article = article1

	article1.R.ArticleShareTargets = append(article1.R.ArticleShareTargets, articleShareTarget0)

	return nil
}

type articleShareTargetWhere[Q psql.Filterable] struct {
	ID          psql.WhereMod[Q, int64]
	ArticleID   psql.WhereMod[Q, int64]
	Provider    psql.WhereMod[Q, string]
	ExternalID  psql.WhereMod[Q, string]
	ExternalURL psql.WhereMod[Q, string]
	PublishedAt psql.WhereNullMod[Q, time.Time]
	CreatedAt   psql.WhereMod[Q, time.Time]
	UpdatedAt   psql.WhereMod[Q, time.Time]
}

func (articleShareTargetWhere[Q]) AliasedAs(alias string) articleShareTargetWhere[Q] {
	return buildArticleShareTargetWhere[Q](buildArticleShareTargetColumns(alias))
}

func buildArticleShareTargetWhere[Q psql.Filterable](cols articleShareTargetColumns) articleShareTargetWhere[Q] {
	return articleShareTargetWhere[Q]{
		ID:          psql.Where[Q, int64](cols.ID),
		ArticleID:   psql.Where[Q, int64](cols.ArticleID),
		Provider:    psql.Where[Q, string](cols.Provider),
		ExternalID:  psql.Where[Q, string](cols.ExternalID),
		ExternalURL: psql.Where[Q, string](cols.ExternalURL),
		PublishedAt: psql.WhereNull[Q, time.Time](cols.PublishedAt),
		CreatedAt:   psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:   psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *ArticleShareTarget) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Article":
		rel, ok := retrieved.(*Article)
		if !ok {
			return fmt.Errorf("articleShareTarget cannot load %T as %q", retrieved, name)
		}

		o.R.Article = rel

		if rel != nil {
			rel.R.ArticleShareTargets = ArticleShareTargetSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("articleShareTarget has no relationship %q", name)
	}
}

type articleShareTargetPreloader struct {
	Article func(...psql.PreloadOption) psql.Preloader
}

func buildArticleShareTargetPreloader() articleShareTargetPreloader {
	return articleShareTargetPreloader{
		Article: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Article, ArticleSlice](psql.PreloadRel{
				Name: "Article",
				Sides: []psql.PreloadSide{
					{
						From:        ArticleShareTargets,
						To:          Articles,
						FromColumns: []string{"article_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Articles.Columns.Names(), opts...)
		},
	}
}

type articleShareTargetThenLoader[Q orm.Loadable] struct {
	Article func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildArticleShareTargetThenLoader[Q orm.Loadable]() articleShareTargetThenLoader[Q] {
	type ArticleLoadInterface interface {
		LoadArticle(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return articleShareTargetThenLoader[Q]{
		Article: thenLoadBuilder[Q](
			"Article",
			func(ctx context.Context, exec bob.Executor, retrieved ArticleLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadArticle(ctx, exec, mods...)
			},
		),
	}
}

// LoadArticle loads the articleShareTarget's Article into the .R struct
func (o *ArticleShareTarget) LoadArticle(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Article = nil

	related, err := o.Article(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.ArticleShareTargets = ArticleShareTargetSlice{o}

	o.R.Article = related
	return nil
}

// LoadArticle loads the articleShareTarget's Article into the .R struct
func (os ArticleShareTargetSlice) LoadArticle(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	articles, err := os.Article(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range articles {

			if !(o.ArticleID == rel.ID) {
				continue
			}

			rel.R.ArticleShareTargets = append(rel.R.ArticleShareTargets, o)

			o.R.Article = rel
			break
		}
	}

	return nil
}

type articleShareTargetJoins[Q dialect.Joinable] struct {
	typ     string
	Article modAs[Q, articleColumns]
}

func (j articleShareTargetJoins[Q]) aliasedAs(alias string) articleShareTargetJoins[Q] {
	return buildArticleShareTargetJoins[Q](buildArticleShareTargetColumns(alias), j.typ)
}

func buildArticleShareTargetJoins[Q dialect.Joinable](cols articleShareTargetColumns, typ string) articleShareTargetJoins[Q] {
	return articleShareTargetJoins[Q]{
		typ: typ,
		Article: modAs[Q, articleColumns]{
			c: Articles.Columns,
			f: func(to articleColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Articles.Name().As(to.Alias())).On(
						to.ID.EQ(cols.ArticleID),
					))
				}

				return mods
			},
		},
	}
}
