// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
)

var (
	SelectWhere     = Where[*dialect.SelectQuery]()
	UpdateWhere     = Where[*dialect.UpdateQuery]()
	DeleteWhere     = Where[*dialect.DeleteQuery]()
	OnConflictWhere = Where[*clause.ConflictClause]() // Used in ON CONFLICT DO UPDATE
)

func Where[Q psql.Filterable]() struct {
	ArticleShareTargets articleShareTargetWhere[Q]
	Articles            articleWhere[Q]
	ExternalTokens      externalTokenWhere[Q]
	PromptRunJobs       promptRunJobWhere[Q]
	Prompts             promptWhere[Q]
	Transcriptions      transcriptionWhere[Q]
	Users               userWhere[Q]
} {
	return struct {
		ArticleShareTargets articleShareTargetWhere[Q]
		Articles            articleWhere[Q]
		ExternalTokens      externalTokenWhere[Q]
		PromptRunJobs       promptRunJobWhere[Q]
		Prompts             promptWhere[Q]
		Transcriptions      transcriptionWhere[Q]
		Users               userWhere[Q]
	}{
		ArticleShareTargets: buildArticleShareTargetWhere[Q](ArticleShareTargets.Columns),
		Articles:            buildArticleWhere[Q](Articles.Columns),
		ExternalTokens:      buildExternalTokenWhere[Q](ExternalTokens.Columns),
		PromptRunJobs:       buildPromptRunJobWhere[Q](PromptRunJobs.Columns),
		Prompts:             buildPromptWhere[Q](Prompts.Columns),
		Transcriptions:      buildTranscriptionWhere[Q](Transcriptions.Columns),
		Users:               buildUserWhere[Q](Users.Columns),
	}
}
