// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// ExternalToken is an object representing the database table.
type ExternalToken struct {
	ID             int64     `db:"id,pk" `
	UserID         int64     `db:"user_id" `
	Provider       string    `db:"provider" `
	EncryptedToken []byte    `db:"encrypted_token" `
	Nonce          []byte    `db:"nonce" `
	CreatedAt      time.Time `db:"created_at" `
	UpdatedAt      time.Time `db:"updated_at" `

	R externalTokenR `db:"-" `
}

// ExternalTokenSlice is an alias for a slice of pointers to ExternalToken.
// This should almost always be used instead of []*ExternalToken.
type ExternalTokenSlice []*ExternalToken

// ExternalTokens contains methods to work with the external_tokens table
var ExternalTokens = psql.NewTablex[*ExternalToken, ExternalTokenSlice, *ExternalTokenSetter]("", "external_tokens", buildExternalTokenColumns("external_tokens"))

// ExternalTokensQuery is a query on the external_tokens table
type ExternalTokensQuery = *psql.ViewQuery[*ExternalToken, ExternalTokenSlice]

// externalTokenR is where relationships are stored.
type externalTokenR struct {
	User *User // external_tokens.external_tokens_user_id_fkey
}

func buildExternalTokenColumns(alias string) externalTokenColumns {
	return externalTokenColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "provider", "encrypted_token", "nonce", "created_at", "updated_at",
		).WithParent("external_tokens"),
		tableAlias:     alias,
		ID:             psql.Quote(alias, "id"),
		UserID:         psql.Quote(alias, "user_id"),
		Provider:       psql.Quote(alias, "provider"),
		EncryptedToken: psql.Quote(alias, "encrypted_token"),
		Nonce:          psql.Quote(alias, "nonce"),
		CreatedAt:      psql.Quote(alias, "created_at"),
		UpdatedAt:      psql.Quote(alias, "updated_at"),
	}
}

type externalTokenColumns struct {
	expr.ColumnsExpr
	tableAlias     string
	ID             psql.Expression
	UserID         psql.Expression
	Provider       psql.Expression
	EncryptedToken psql.Expression
	Nonce          psql.Expression
	CreatedAt      psql.Expression
	UpdatedAt      psql.Expression
}

func (c externalTokenColumns) Alias() string {
	return c.tableAlias
}

func (externalTokenColumns) AliasedAs(alias string) externalTokenColumns {
	return buildExternalTokenColumns(alias)
}

// ExternalTokenSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ExternalTokenSetter struct {
	ID             omit.Val[int64]     `db:"id,pk" `
	UserID         omit.Val[int64]     `db:"user_id" `
	Provider       omit.Val[string]    `db:"provider" `
	EncryptedToken omit.Val[[]byte]    `db:"encrypted_token" `
	Nonce          omit.Val[[]byte]    `db:"nonce" `
	CreatedAt      omit.Val[time.Time] `db:"created_at" `
	UpdatedAt      omit.Val[time.Time] `db:"updated_at" `
}

func (s ExternalTokenSetter) SetColumns() []string {
	vals := make([]string, 0, 7)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.Provider.IsValue() {
		vals = append(vals, "provider")
	}
	if s.EncryptedToken.IsValue() {
		vals = append(vals, "encrypted_token")
	}
	if s.Nonce.IsValue() {
		vals = append(vals, "nonce")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s ExternalTokenSetter) Overwrite(t *ExternalToken) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.Provider.IsValue() {
		t.Provider = s.Provider.MustGet()
	}
	if s.EncryptedToken.IsValue() {
		t.EncryptedToken = s.EncryptedToken.MustGet()
	}
	if s.Nonce.IsValue() {
		t.Nonce = s.Nonce.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *ExternalTokenSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return ExternalTokens.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 7)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[1] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Provider.IsValue() {
			vals[2] = psql.Arg(s.Provider.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.EncryptedToken.IsValue() {
			vals[3] = psql.Arg(s.EncryptedToken.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.Nonce.IsValue() {
			vals[4] = psql.Arg(s.Nonce.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[5] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[6] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s ExternalTokenSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ExternalTokenSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 7)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.Provider.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "provider")...),
			psql.Arg(s.Provider),
		}})
	}

	if s.EncryptedToken.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "encrypted_token")...),
			psql.Arg(s.EncryptedToken),
		}})
	}

	if s.Nonce.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "nonce")...),
			psql.Arg(s.Nonce),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindExternalToken retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindExternalToken(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*ExternalToken, error) {
	if len(cols) == 0 {
		return ExternalTokens.Query(
			sm.Where(ExternalTokens.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return ExternalTokens.Query(
		sm.Where(ExternalTokens.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(ExternalTokens.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ExternalTokenExists checks the presence of a single record by primary key
func ExternalTokenExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return ExternalTokens.Query(
		sm.Where(ExternalTokens.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after ExternalToken is retrieved from the database
func (o *ExternalToken) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ExternalTokens.AfterSelectHooks.RunHooks(ctx, exec, ExternalTokenSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = ExternalTokens.AfterInsertHooks.RunHooks(ctx, exec, ExternalTokenSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = ExternalTokens.AfterUpdateHooks.RunHooks(ctx, exec, ExternalTokenSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = ExternalTokens.AfterDeleteHooks.RunHooks(ctx, exec, ExternalTokenSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the ExternalToken
func (o *ExternalToken) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *ExternalToken) pkEQ() dialect.Expression {
	return psql.Quote("external_tokens", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the ExternalToken
func (o *ExternalToken) Update(ctx context.Context, exec bob.Executor, s *ExternalTokenSetter) error {
	v, err := ExternalTokens.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single ExternalToken record with an executor
func (o *ExternalToken) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := ExternalTokens.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the ExternalToken using the executor
func (o *ExternalToken) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := ExternalTokens.Query(
		sm.Where(ExternalTokens.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ExternalTokenSlice is retrieved from the database
func (o ExternalTokenSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ExternalTokens.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = ExternalTokens.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = ExternalTokens.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = ExternalTokens.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ExternalTokenSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("external_tokens", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ExternalTokenSlice) copyMatchingRows(from ...*ExternalToken) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ExternalTokenSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ExternalTokens.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ExternalToken:
				o.copyMatchingRows(retrieved)
			case []*ExternalToken:
				o.copyMatchingRows(retrieved...)
			case ExternalTokenSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ExternalToken or a slice of ExternalToken
				// then run the AfterUpdateHooks on the slice
				_, err = ExternalTokens.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ExternalTokenSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ExternalTokens.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ExternalToken:
				o.copyMatchingRows(retrieved)
			case []*ExternalToken:
				o.copyMatchingRows(retrieved...)
			case ExternalTokenSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ExternalToken or a slice of ExternalToken
				// then run the AfterDeleteHooks on the slice
				_, err = ExternalTokens.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ExternalTokenSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ExternalTokenSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ExternalTokens.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ExternalTokenSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ExternalTokens.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ExternalTokenSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := ExternalTokens.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// User starts a query for related objects on users
func (o *ExternalToken) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os ExternalTokenSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "bigint[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachExternalTokenUser0(ctx context.Context, exec bob.Executor, count int, externalToken0 *ExternalToken, user1 *User) (*ExternalToken, error) {
	setter := &ExternalTokenSetter{
		UserID: omit.From(user1.ID),
	}

	err := externalToken0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachExternalTokenUser0: %w", err)
	}

	return externalToken0, nil
}

func (externalToken0 *ExternalToken) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachExternalTokenUser0(ctx, exec, 1, externalToken0, user1)
	if err != nil {
		return err
	}

	externalToken0.R.User = user1

	user1.R.ExternalTokens = append(user1.R.ExternalTokens, externalToken0)

	return nil
}

func (externalToken0 *ExternalToken) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachExternalTokenUser0(ctx, exec, 1, externalToken0, user1)
	if err != nil {
		return err
	}

	externalToken0.R.User = user1

	user1.R.ExternalTokens = append(user1.R.ExternalTokens, externalToken0)

	return nil
}

type externalTokenWhere[Q psql.Filterable] struct {
	ID             psql.WhereMod[Q, int64]
	UserID         psql.WhereMod[Q, int64]
	Provider       psql.WhereMod[Q, string]
	EncryptedToken psql.WhereMod[Q, []byte]
	Nonce          psql.WhereMod[Q, []byte]
	CreatedAt      psql.WhereMod[Q, time.Time]
	UpdatedAt      psql.WhereMod[Q, time.Time]
}

func (externalTokenWhere[Q]) AliasedAs(alias string) externalTokenWhere[Q] {
	return buildExternalTokenWhere[Q](buildExternalTokenColumns(alias))
}

func buildExternalTokenWhere[Q psql.Filterable](cols externalTokenColumns) externalTokenWhere[Q] {
	return externalTokenWhere[Q]{
		ID:             psql.Where[Q, int64](cols.ID),
		UserID:         psql.Where[Q, int64](cols.UserID),
		Provider:       psql.Where[Q, string](cols.Provider),
		EncryptedToken: psql.Where[Q, []byte](cols.EncryptedToken),
		Nonce:          psql.Where[Q, []byte](cols.Nonce),
		CreatedAt:      psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:      psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *ExternalToken) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("externalToken cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.ExternalTokens = ExternalTokenSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("externalToken has no relationship %q", name)
	}
}

type externalTokenPreloader struct {
	User func(...psql.PreloadOption) psql.Preloader
}

func buildExternalTokenPreloader() externalTokenPreloader {
	return externalTokenPreloader{
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        ExternalTokens,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type externalTokenThenLoader[Q orm.Loadable] struct {
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildExternalTokenThenLoader[Q orm.Loadable]() externalTokenThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return externalTokenThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the externalToken's User into the .R struct
func (o *ExternalToken) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.ExternalTokens = ExternalTokenSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the externalToken's User into the .R struct
func (os ExternalTokenSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.ExternalTokens = append(rel.R.ExternalTokens, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type externalTokenJoins[Q dialect.Joinable] struct {
	typ  string
	User modAs[Q, userColumns]
}

func (j externalTokenJoins[Q]) aliasedAs(alias string) externalTokenJoins[Q] {
	return buildExternalTokenJoins[Q](buildExternalTokenColumns(alias), j.typ)
}

func buildExternalTokenJoins[Q dialect.Joinable](cols externalTokenColumns, typ string) externalTokenJoins[Q] {
	return externalTokenJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
