// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// PromptRunJob is an object representing the database table.
type PromptRunJob struct {
	ID               int64            `db:"id,pk" `
	TranscriptionID  int64            `db:"transcription_id" `
	PromptID         int64            `db:"prompt_id" `
	Status           string           `db:"status" `
	AttemptCount     int32            `db:"attempt_count" `
	NextRunAt        time.Time        `db:"next_run_at" `
	ErrorMessage     null.Val[string] `db:"error_message" `
	CreatedAt        time.Time        `db:"created_at" `
	GeneratedTitle   null.Val[string] `db:"generated_title" `
	GeneratedContent null.Val[string] `db:"generated_content" `

	R promptRunJobR `db:"-" `
}

// PromptRunJobSlice is an alias for a slice of pointers to PromptRunJob.
// This should almost always be used instead of []*PromptRunJob.
type PromptRunJobSlice []*PromptRunJob

// PromptRunJobs contains methods to work with the prompt_run_jobs table
var PromptRunJobs = psql.NewTablex[*PromptRunJob, PromptRunJobSlice, *PromptRunJobSetter]("", "prompt_run_jobs", buildPromptRunJobColumns("prompt_run_jobs"))

// PromptRunJobsQuery is a query on the prompt_run_jobs table
type PromptRunJobsQuery = *psql.ViewQuery[*PromptRunJob, PromptRunJobSlice]

// promptRunJobR is where relationships are stored.
type promptRunJobR struct {
	Article       *Article       // articles.articles_prompt_run_job_id_fkey
	Prompt        *Prompt        // prompt_run_jobs.prompt_run_jobs_prompt_id_fkey
	Transcription *Transcription // prompt_run_jobs.prompt_run_jobs_transcription_id_fkey
}

func buildPromptRunJobColumns(alias string) promptRunJobColumns {
	return promptRunJobColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "transcription_id", "prompt_id", "status", "attempt_count", "next_run_at", "error_message", "created_at", "generated_title", "generated_content",
		).WithParent("prompt_run_jobs"),
		tableAlias:       alias,
		ID:               psql.Quote(alias, "id"),
		TranscriptionID:  psql.Quote(alias, "transcription_id"),
		PromptID:         psql.Quote(alias, "prompt_id"),
		Status:           psql.Quote(alias, "status"),
		AttemptCount:     psql.Quote(alias, "attempt_count"),
		NextRunAt:        psql.Quote(alias, "next_run_at"),
		ErrorMessage:     psql.Quote(alias, "error_message"),
		CreatedAt:        psql.Quote(alias, "created_at"),
		GeneratedTitle:   psql.Quote(alias, "generated_title"),
		GeneratedContent: psql.Quote(alias, "generated_content"),
	}
}

type promptRunJobColumns struct {
	expr.ColumnsExpr
	tableAlias       string
	ID               psql.Expression
	TranscriptionID  psql.Expression
	PromptID         psql.Expression
	Status           psql.Expression
	AttemptCount     psql.Expression
	NextRunAt        psql.Expression
	ErrorMessage     psql.Expression
	CreatedAt        psql.Expression
	GeneratedTitle   psql.Expression
	GeneratedContent psql.Expression
}

func (c promptRunJobColumns) Alias() string {
	return c.tableAlias
}

func (promptRunJobColumns) AliasedAs(alias string) promptRunJobColumns {
	return buildPromptRunJobColumns(alias)
}

// PromptRunJobSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type PromptRunJobSetter struct {
	ID               omit.Val[int64]      `db:"id,pk" `
	TranscriptionID  omit.Val[int64]      `db:"transcription_id" `
	PromptID         omit.Val[int64]      `db:"prompt_id" `
	Status           omit.Val[string]     `db:"status" `
	AttemptCount     omit.Val[int32]      `db:"attempt_count" `
	NextRunAt        omit.Val[time.Time]  `db:"next_run_at" `
	ErrorMessage     omitnull.Val[string] `db:"error_message" `
	CreatedAt        omit.Val[time.Time]  `db:"created_at" `
	GeneratedTitle   omitnull.Val[string] `db:"generated_title" `
	GeneratedContent omitnull.Val[string] `db:"generated_content" `
}

func (s PromptRunJobSetter) SetColumns() []string {
	vals := make([]string, 0, 10)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.TranscriptionID.IsValue() {
		vals = append(vals, "transcription_id")
	}
	if s.PromptID.IsValue() {
		vals = append(vals, "prompt_id")
	}
	if s.Status.IsValue() {
		vals = append(vals, "status")
	}
	if s.AttemptCount.IsValue() {
		vals = append(vals, "attempt_count")
	}
	if s.NextRunAt.IsValue() {
		vals = append(vals, "next_run_at")
	}
	if !s.ErrorMessage.IsUnset() {
		vals = append(vals, "error_message")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if !s.GeneratedTitle.IsUnset() {
		vals = append(vals, "generated_title")
	}
	if !s.GeneratedContent.IsUnset() {
		vals = append(vals, "generated_content")
	}
	return vals
}

func (s PromptRunJobSetter) Overwrite(t *PromptRunJob) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.TranscriptionID.IsValue() {
		t.TranscriptionID = s.TranscriptionID.MustGet()
	}
	if s.PromptID.IsValue() {
		t.PromptID = s.PromptID.MustGet()
	}
	if s.Status.IsValue() {
		t.Status = s.Status.MustGet()
	}
	if s.AttemptCount.IsValue() {
		t.AttemptCount = s.AttemptCount.MustGet()
	}
	if s.NextRunAt.IsValue() {
		t.NextRunAt = s.NextRunAt.MustGet()
	}
	if !s.ErrorMessage.IsUnset() {
		t.ErrorMessage = s.ErrorMessage.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if !s.GeneratedTitle.IsUnset() {
		t.GeneratedTitle = s.GeneratedTitle.MustGetNull()
	}
	if !s.GeneratedContent.IsUnset() {
		t.GeneratedContent = s.GeneratedContent.MustGetNull()
	}
}

func (s *PromptRunJobSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return PromptRunJobs.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 10)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.TranscriptionID.IsValue() {
			vals[1] = psql.Arg(s.TranscriptionID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.PromptID.IsValue() {
			vals[2] = psql.Arg(s.PromptID.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Status.IsValue() {
			vals[3] = psql.Arg(s.Status.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.AttemptCount.IsValue() {
			vals[4] = psql.Arg(s.AttemptCount.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.NextRunAt.IsValue() {
			vals[5] = psql.Arg(s.NextRunAt.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if !s.ErrorMessage.IsUnset() {
			vals[6] = psql.Arg(s.ErrorMessage.MustGetNull())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[7] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if !s.GeneratedTitle.IsUnset() {
			vals[8] = psql.Arg(s.GeneratedTitle.MustGetNull())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if !s.GeneratedContent.IsUnset() {
			vals[9] = psql.Arg(s.GeneratedContent.MustGetNull())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s PromptRunJobSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s PromptRunJobSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 10)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.TranscriptionID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "transcription_id")...),
			psql.Arg(s.TranscriptionID),
		}})
	}

	if s.PromptID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "prompt_id")...),
			psql.Arg(s.PromptID),
		}})
	}

	if s.Status.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "status")...),
			psql.Arg(s.Status),
		}})
	}

	if s.AttemptCount.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "attempt_count")...),
			psql.Arg(s.AttemptCount),
		}})
	}

	if s.NextRunAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "next_run_at")...),
			psql.Arg(s.NextRunAt),
		}})
	}

	if !s.ErrorMessage.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "error_message")...),
			psql.Arg(s.ErrorMessage),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if !s.GeneratedTitle.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "generated_title")...),
			psql.Arg(s.GeneratedTitle),
		}})
	}

	if !s.GeneratedContent.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "generated_content")...),
			psql.Arg(s.GeneratedContent),
		}})
	}

	return exprs
}

// FindPromptRunJob retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindPromptRunJob(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*PromptRunJob, error) {
	if len(cols) == 0 {
		return PromptRunJobs.Query(
			sm.Where(PromptRunJobs.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return PromptRunJobs.Query(
		sm.Where(PromptRunJobs.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(PromptRunJobs.Columns.Only(cols...)),
	).One(ctx, exec)
}

// PromptRunJobExists checks the presence of a single record by primary key
func PromptRunJobExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return PromptRunJobs.Query(
		sm.Where(PromptRunJobs.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after PromptRunJob is retrieved from the database
func (o *PromptRunJob) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = PromptRunJobs.AfterSelectHooks.RunHooks(ctx, exec, PromptRunJobSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = PromptRunJobs.AfterInsertHooks.RunHooks(ctx, exec, PromptRunJobSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = PromptRunJobs.AfterUpdateHooks.RunHooks(ctx, exec, PromptRunJobSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = PromptRunJobs.AfterDeleteHooks.RunHooks(ctx, exec, PromptRunJobSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the PromptRunJob
func (o *PromptRunJob) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *PromptRunJob) pkEQ() dialect.Expression {
	return psql.Quote("prompt_run_jobs", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the PromptRunJob
func (o *PromptRunJob) Update(ctx context.Context, exec bob.Executor, s *PromptRunJobSetter) error {
	v, err := PromptRunJobs.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single PromptRunJob record with an executor
func (o *PromptRunJob) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := PromptRunJobs.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the PromptRunJob using the executor
func (o *PromptRunJob) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := PromptRunJobs.Query(
		sm.Where(PromptRunJobs.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after PromptRunJobSlice is retrieved from the database
func (o PromptRunJobSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = PromptRunJobs.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = PromptRunJobs.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = PromptRunJobs.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = PromptRunJobs.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o PromptRunJobSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("prompt_run_jobs", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o PromptRunJobSlice) copyMatchingRows(from ...*PromptRunJob) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o PromptRunJobSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PromptRunJobs.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PromptRunJob:
				o.copyMatchingRows(retrieved)
			case []*PromptRunJob:
				o.copyMatchingRows(retrieved...)
			case PromptRunJobSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PromptRunJob or a slice of PromptRunJob
				// then run the AfterUpdateHooks on the slice
				_, err = PromptRunJobs.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o PromptRunJobSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PromptRunJobs.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PromptRunJob:
				o.copyMatchingRows(retrieved)
			case []*PromptRunJob:
				o.copyMatchingRows(retrieved...)
			case PromptRunJobSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PromptRunJob or a slice of PromptRunJob
				// then run the AfterDeleteHooks on the slice
				_, err = PromptRunJobs.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o PromptRunJobSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals PromptRunJobSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := PromptRunJobs.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o PromptRunJobSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := PromptRunJobs.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o PromptRunJobSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := PromptRunJobs.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Article starts a query for related objects on articles
func (o *PromptRunJob) Article(mods ...bob.Mod[*dialect.SelectQuery]) ArticlesQuery {
	return Articles.Query(append(mods,
		sm.Where(Articles.Columns.PromptRunJobID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os PromptRunJobSlice) Article(mods ...bob.Mod[*dialect.SelectQuery]) ArticlesQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return Articles.Query(append(mods,
		sm.Where(psql.Group(Articles.Columns.PromptRunJobID).OP("IN", PKArgExpr)),
	)...)
}

// Prompt starts a query for related objects on prompts
func (o *PromptRunJob) Prompt(mods ...bob.Mod[*dialect.SelectQuery]) PromptsQuery {
	return Prompts.Query(append(mods,
		sm.Where(Prompts.Columns.ID.EQ(psql.Arg(o.PromptID))),
	)...)
}

func (os PromptRunJobSlice) Prompt(mods ...bob.Mod[*dialect.SelectQuery]) PromptsQuery {
	pkPromptID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkPromptID = append(pkPromptID, o.PromptID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkPromptID), "bigint[]")),
	))

	return Prompts.Query(append(mods,
		sm.Where(psql.Group(Prompts.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// Transcription starts a query for related objects on transcriptions
func (o *PromptRunJob) Transcription(mods ...bob.Mod[*dialect.SelectQuery]) TranscriptionsQuery {
	return Transcriptions.Query(append(mods,
		sm.Where(Transcriptions.Columns.ID.EQ(psql.Arg(o.TranscriptionID))),
	)...)
}

func (os PromptRunJobSlice) Transcription(mods ...bob.Mod[*dialect.SelectQuery]) TranscriptionsQuery {
	pkTranscriptionID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkTranscriptionID = append(pkTranscriptionID, o.TranscriptionID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkTranscriptionID), "bigint[]")),
	))

	return Transcriptions.Query(append(mods,
		sm.Where(psql.Group(Transcriptions.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func insertPromptRunJobArticle0(ctx context.Context, exec bob.Executor, article1 *ArticleSetter, promptRunJob0 *PromptRunJob) (*Article, error) {
	article1.PromptRunJobID = omitnull.From(promptRunJob0.ID)

	ret, err := Articles.Insert(article1).One(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertPromptRunJobArticle0: %w", err)
	}

	return ret, nil
}

func attachPromptRunJobArticle0(ctx context.Context, exec bob.Executor, count int, article1 *Article, promptRunJob0 *PromptRunJob) (*Article, error) {
	setter := &ArticleSetter{
		PromptRunJobID: omitnull.From(promptRunJob0.ID),
	}

	err := article1.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachPromptRunJobArticle0: %w", err)
	}

	return article1, nil
}

func (promptRunJob0 *PromptRunJob) InsertArticle(ctx context.Context, exec bob.Executor, related *ArticleSetter) error {
	var err error

	article1, err := insertPromptRunJobArticle0(ctx, exec, related, promptRunJob0)
	if err != nil {
		return err
	}

	promptRunJob0.R.Article = article1

	article1.R.PromptRunJob = promptRunJob0

	return nil
}

func (promptRunJob0 *PromptRunJob) AttachArticle(ctx context.Context, exec bob.Executor, article1 *Article) error {
	var err error

	_, err = attachPromptRunJobArticle0(ctx, exec, 1, article1, promptRunJob0)
	if err != nil {
		return err
	}

	promptRunJob0.R.Article = article1

	article1.R.PromptRunJob = promptRunJob0

	return nil
}

func attachPromptRunJobPrompt0(ctx context.Context, exec bob.Executor, count int, promptRunJob0 *PromptRunJob, prompt1 *Prompt) (*PromptRunJob, error) {
	setter := &PromptRunJobSetter{
		PromptID: omit.From(prompt1.ID),
	}

	err := promptRunJob0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachPromptRunJobPrompt0: %w", err)
	}

	return promptRunJob0, nil
}

func (promptRunJob0 *PromptRunJob) InsertPrompt(ctx context.Context, exec bob.Executor, related *PromptSetter) error {
	var err error

	prompt1, err := Prompts.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachPromptRunJobPrompt0(ctx, exec, 1, promptRunJob0, prompt1)
	if err != nil {
		return err
	}

	promptRunJob0.R.Prompt = prompt1

	prompt1.R.PromptRunJobs = append(prompt1.R.PromptRunJobs, promptRunJob0)

	return nil
}

func (promptRunJob0 *PromptRunJob) AttachPrompt(ctx context.Context, exec bob.Executor, prompt1 *Prompt) error {
	var err error

	_, err = attachPromptRunJobPrompt0(ctx, exec, 1, promptRunJob0, prompt1)
	if err != nil {
		return err
	}

	promptRunJob0.R.Prompt = prompt1

	prompt1.R.PromptRunJobs = append(prompt1.R.PromptRunJobs, promptRunJob0)

	return nil
}

func attachPromptRunJobTranscription0(ctx context.Context, exec bob.Executor, count int, promptRunJob0 *PromptRunJob, transcription1 *Transcription) (*PromptRunJob, error) {
	setter := &PromptRunJobSetter{
		TranscriptionID: omit.From(transcription1.ID),
	}

	err := promptRunJob0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachPromptRunJobTranscription0: %w", err)
	}

	return promptRunJob0, nil
}

func (promptRunJob0 *PromptRunJob) InsertTranscription(ctx context.Context, exec bob.Executor, related *TranscriptionSetter) error {
	var err error

	transcription1, err := Transcriptions.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachPromptRunJobTranscription0(ctx, exec, 1, promptRunJob0, transcription1)
	if err != nil {
		return err
	}

	promptRunJob0.R.Transcription = transcription1

	transcription1.R.PromptRunJobs = append(transcription1.R.PromptRunJobs, promptRunJob0)

	return nil
}

func (promptRunJob0 *PromptRunJob) AttachTranscription(ctx context.Context, exec bob.Executor, transcription1 *Transcription) error {
	var err error

	_, err = attachPromptRunJobTranscription0(ctx, exec, 1, promptRunJob0, transcription1)
	if err != nil {
		return err
	}

	promptRunJob0.R.Transcription = transcription1

	transcription1.R.PromptRunJobs = append(transcription1.R.PromptRunJobs, promptRunJob0)

	return nil
}

type promptRunJobWhere[Q psql.Filterable] struct {
	ID               psql.WhereMod[Q, int64]
	TranscriptionID  psql.WhereMod[Q, int64]
	PromptID         psql.WhereMod[Q, int64]
	Status           psql.WhereMod[Q, string]
	AttemptCount     psql.WhereMod[Q, int32]
	NextRunAt        psql.WhereMod[Q, time.Time]
	ErrorMessage     psql.WhereNullMod[Q, string]
	CreatedAt        psql.WhereMod[Q, time.Time]
	GeneratedTitle   psql.WhereNullMod[Q, string]
	GeneratedContent psql.WhereNullMod[Q, string]
}

func (promptRunJobWhere[Q]) AliasedAs(alias string) promptRunJobWhere[Q] {
	return buildPromptRunJobWhere[Q](buildPromptRunJobColumns(alias))
}

func buildPromptRunJobWhere[Q psql.Filterable](cols promptRunJobColumns) promptRunJobWhere[Q] {
	return promptRunJobWhere[Q]{
		ID:               psql.Where[Q, int64](cols.ID),
		TranscriptionID:  psql.Where[Q, int64](cols.TranscriptionID),
		PromptID:         psql.Where[Q, int64](cols.PromptID),
		Status:           psql.Where[Q, string](cols.Status),
		AttemptCount:     psql.Where[Q, int32](cols.AttemptCount),
		NextRunAt:        psql.Where[Q, time.Time](cols.NextRunAt),
		ErrorMessage:     psql.WhereNull[Q, string](cols.ErrorMessage),
		CreatedAt:        psql.Where[Q, time.Time](cols.CreatedAt),
		GeneratedTitle:   psql.WhereNull[Q, string](cols.GeneratedTitle),
		GeneratedContent: psql.WhereNull[Q, string](cols.GeneratedContent),
	}
}

func (o *PromptRunJob) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Article":
		rel, ok := retrieved.(*Article)
		if !ok {
			return fmt.Errorf("promptRunJob cannot load %T as %q", retrieved, name)
		}

		o.R.Article = rel

		if rel != nil {
			rel.R.PromptRunJob = o
		}
		return nil
	case "Prompt":
		rel, ok := retrieved.(*Prompt)
		if !ok {
			return fmt.Errorf("promptRunJob cannot load %T as %q", retrieved, name)
		}

		o.R.Prompt = rel

		if rel != nil {
			rel.R.PromptRunJobs = PromptRunJobSlice{o}
		}
		return nil
	case "Transcription":
		rel, ok := retrieved.(*Transcription)
		if !ok {
			return fmt.Errorf("promptRunJob cannot load %T as %q", retrieved, name)
		}

		o.R.Transcription = rel

		if rel != nil {
			rel.R.PromptRunJobs = PromptRunJobSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("promptRunJob has no relationship %q", name)
	}
}

type promptRunJobPreloader struct {
	Article       func(...psql.PreloadOption) psql.Preloader
	Prompt        func(...psql.PreloadOption) psql.Preloader
	Transcription func(...psql.PreloadOption) psql.Preloader
}

func buildPromptRunJobPreloader() promptRunJobPreloader {
	return promptRunJobPreloader{
		Article: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Article, ArticleSlice](psql.PreloadRel{
				Name: "Article",
				Sides: []psql.PreloadSide{
					{
						From:        PromptRunJobs,
						To:          Articles,
						FromColumns: []string{"id"},
						ToColumns:   []string{"prompt_run_job_id"},
					},
				},
			}, Articles.Columns.Names(), opts...)
		},
		Prompt: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Prompt, PromptSlice](psql.PreloadRel{
				Name: "Prompt",
				Sides: []psql.PreloadSide{
					{
						From:        PromptRunJobs,
						To:          Prompts,
						FromColumns: []string{"prompt_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Prompts.Columns.Names(), opts...)
		},
		Transcription: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Transcription, TranscriptionSlice](psql.PreloadRel{
				Name: "Transcription",
				Sides: []psql.PreloadSide{
					{
						From:        PromptRunJobs,
						To:          Transcriptions,
						FromColumns: []string{"transcription_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Transcriptions.Columns.Names(), opts...)
		},
	}
}

type promptRunJobThenLoader[Q orm.Loadable] struct {
	Article       func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Prompt        func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Transcription func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildPromptRunJobThenLoader[Q orm.Loadable]() promptRunJobThenLoader[Q] {
	type ArticleLoadInterface interface {
		LoadArticle(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type PromptLoadInterface interface {
		LoadPrompt(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TranscriptionLoadInterface interface {
		LoadTranscription(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return promptRunJobThenLoader[Q]{
		Article: thenLoadBuilder[Q](
			"Article",
			func(ctx context.Context, exec bob.Executor, retrieved ArticleLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadArticle(ctx, exec, mods...)
			},
		),
		Prompt: thenLoadBuilder[Q](
			"Prompt",
			func(ctx context.Context, exec bob.Executor, retrieved PromptLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadPrompt(ctx, exec, mods...)
			},
		),
		Transcription: thenLoadBuilder[Q](
			"Transcription",
			func(ctx context.Context, exec bob.Executor, retrieved TranscriptionLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTranscription(ctx, exec, mods...)
			},
		),
	}
}

// LoadArticle loads the promptRunJob's Article into the .R struct
func (o *PromptRunJob) LoadArticle(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Article = nil

	related, err := o.Article(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.PromptRunJob = o

	o.R.Article = related
	return nil
}

// LoadArticle loads the promptRunJob's Article into the .R struct
func (os PromptRunJobSlice) LoadArticle(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	articles, err := os.Article(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range articles {

			if !rel.PromptRunJobID.IsValue() {
				continue
			}
			if !(rel.PromptRunJobID.IsValue() && o.ID == rel.PromptRunJobID.MustGet()) {
				continue
			}

			rel.R.PromptRunJob = o

			o.R.Article = rel
			break
		}
	}

	return nil
}

// LoadPrompt loads the promptRunJob's Prompt into the .R struct
func (o *PromptRunJob) LoadPrompt(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Prompt = nil

	related, err := o.Prompt(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.PromptRunJobs = PromptRunJobSlice{o}

	o.R.Prompt = related
	return nil
}

// LoadPrompt loads the promptRunJob's Prompt into the .R struct
func (os PromptRunJobSlice) LoadPrompt(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	prompts, err := os.Prompt(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range prompts {

			if !(o.PromptID == rel.ID) {
				continue
			}

			rel.R.PromptRunJobs = append(rel.R.PromptRunJobs, o)

			o.R.Prompt = rel
			break
		}
	}

	return nil
}

// LoadTranscription loads the promptRunJob's Transcription into the .R struct
func (o *PromptRunJob) LoadTranscription(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Transcription = nil

	related, err := o.Transcription(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.PromptRunJobs = PromptRunJobSlice{o}

	o.R.Transcription = related
	return nil
}

// LoadTranscription loads the promptRunJob's Transcription into the .R struct
func (os PromptRunJobSlice) LoadTranscription(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	transcriptions, err := os.Transcription(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range transcriptions {

			if !(o.TranscriptionID == rel.ID) {
				continue
			}

			rel.R.PromptRunJobs = append(rel.R.PromptRunJobs, o)

			o.R.Transcription = rel
			break
		}
	}

	return nil
}

type promptRunJobJoins[Q dialect.Joinable] struct {
	typ           string
	Article       modAs[Q, articleColumns]
	Prompt        modAs[Q, promptColumns]
	Transcription modAs[Q, transcriptionColumns]
}

func (j promptRunJobJoins[Q]) aliasedAs(alias string) promptRunJobJoins[Q] {
	return buildPromptRunJobJoins[Q](buildPromptRunJobColumns(alias), j.typ)
}

func buildPromptRunJobJoins[Q dialect.Joinable](cols promptRunJobColumns, typ string) promptRunJobJoins[Q] {
	return promptRunJobJoins[Q]{
		typ: typ,
		Article: modAs[Q, articleColumns]{
			c: Articles.Columns,
			f: func(to articleColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Articles.Name().As(to.Alias())).On(
						to.PromptRunJobID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Prompt: modAs[Q, promptColumns]{
			c: Prompts.Columns,
			f: func(to promptColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Prompts.Name().As(to.Alias())).On(
						to.ID.EQ(cols.PromptID),
					))
				}

				return mods
			},
		},
		Transcription: modAs[Q, transcriptionColumns]{
			c: Transcriptions.Columns,
			f: func(to transcriptionColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Transcriptions.Name().As(to.Alias())).On(
						to.ID.EQ(cols.TranscriptionID),
					))
				}

				return mods
			},
		},
	}
}
