// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Prompt is an object representing the database table.
type Prompt struct {
	ID        int64           `db:"id,pk" `
	UserID    null.Val[int64] `db:"user_id" `
	Name      string          `db:"name" `
	Body      string          `db:"body" `
	IsActive  bool            `db:"is_active" `
	IsDefault bool            `db:"is_default" `
	CreatedAt time.Time       `db:"created_at" `
	UpdatedAt time.Time       `db:"updated_at" `

	R promptR `db:"-" `
}

// PromptSlice is an alias for a slice of pointers to Prompt.
// This should almost always be used instead of []*Prompt.
type PromptSlice []*Prompt

// Prompts contains methods to work with the prompts table
var Prompts = psql.NewTablex[*Prompt, PromptSlice, *PromptSetter]("", "prompts", buildPromptColumns("prompts"))

// PromptsQuery is a query on the prompts table
type PromptsQuery = *psql.ViewQuery[*Prompt, PromptSlice]

// promptR is where relationships are stored.
type promptR struct {
	PromptRunJobs PromptRunJobSlice // prompt_run_jobs.prompt_run_jobs_prompt_id_fkey
	User          *User             // prompts.prompts_user_id_fkey
}

func buildPromptColumns(alias string) promptColumns {
	return promptColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "name", "body", "is_active", "is_default", "created_at", "updated_at",
		).WithParent("prompts"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		UserID:     psql.Quote(alias, "user_id"),
		Name:       psql.Quote(alias, "name"),
		Body:       psql.Quote(alias, "body"),
		IsActive:   psql.Quote(alias, "is_active"),
		IsDefault:  psql.Quote(alias, "is_default"),
		CreatedAt:  psql.Quote(alias, "created_at"),
		UpdatedAt:  psql.Quote(alias, "updated_at"),
	}
}

type promptColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	UserID     psql.Expression
	Name       psql.Expression
	Body       psql.Expression
	IsActive   psql.Expression
	IsDefault  psql.Expression
	CreatedAt  psql.Expression
	UpdatedAt  psql.Expression
}

func (c promptColumns) Alias() string {
	return c.tableAlias
}

func (promptColumns) AliasedAs(alias string) promptColumns {
	return buildPromptColumns(alias)
}

// PromptSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type PromptSetter struct {
	ID        omit.Val[int64]     `db:"id,pk" `
	UserID    omitnull.Val[int64] `db:"user_id" `
	Name      omit.Val[string]    `db:"name" `
	Body      omit.Val[string]    `db:"body" `
	IsActive  omit.Val[bool]      `db:"is_active" `
	IsDefault omit.Val[bool]      `db:"is_default" `
	CreatedAt omit.Val[time.Time] `db:"created_at" `
	UpdatedAt omit.Val[time.Time] `db:"updated_at" `
}

func (s PromptSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if !s.UserID.IsUnset() {
		vals = append(vals, "user_id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.Body.IsValue() {
		vals = append(vals, "body")
	}
	if s.IsActive.IsValue() {
		vals = append(vals, "is_active")
	}
	if s.IsDefault.IsValue() {
		vals = append(vals, "is_default")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s PromptSetter) Overwrite(t *Prompt) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if !s.UserID.IsUnset() {
		t.UserID = s.UserID.MustGetNull()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.Body.IsValue() {
		t.Body = s.Body.MustGet()
	}
	if s.IsActive.IsValue() {
		t.IsActive = s.IsActive.MustGet()
	}
	if s.IsDefault.IsValue() {
		t.IsDefault = s.IsDefault.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *PromptSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Prompts.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 8)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if !s.UserID.IsUnset() {
			vals[1] = psql.Arg(s.UserID.MustGetNull())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[2] = psql.Arg(s.Name.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Body.IsValue() {
			vals[3] = psql.Arg(s.Body.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.IsActive.IsValue() {
			vals[4] = psql.Arg(s.IsActive.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.IsDefault.IsValue() {
			vals[5] = psql.Arg(s.IsDefault.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[6] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[7] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s PromptSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s PromptSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if !s.UserID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.Body.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "body")...),
			psql.Arg(s.Body),
		}})
	}

	if s.IsActive.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_active")...),
			psql.Arg(s.IsActive),
		}})
	}

	if s.IsDefault.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_default")...),
			psql.Arg(s.IsDefault),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindPrompt retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindPrompt(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Prompt, error) {
	if len(cols) == 0 {
		return Prompts.Query(
			sm.Where(Prompts.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Prompts.Query(
		sm.Where(Prompts.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Prompts.Columns.Only(cols...)),
	).One(ctx, exec)
}

// PromptExists checks the presence of a single record by primary key
func PromptExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Prompts.Query(
		sm.Where(Prompts.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Prompt is retrieved from the database
func (o *Prompt) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Prompts.AfterSelectHooks.RunHooks(ctx, exec, PromptSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Prompts.AfterInsertHooks.RunHooks(ctx, exec, PromptSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Prompts.AfterUpdateHooks.RunHooks(ctx, exec, PromptSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Prompts.AfterDeleteHooks.RunHooks(ctx, exec, PromptSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Prompt
func (o *Prompt) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Prompt) pkEQ() dialect.Expression {
	return psql.Quote("prompts", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Prompt
func (o *Prompt) Update(ctx context.Context, exec bob.Executor, s *PromptSetter) error {
	v, err := Prompts.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Prompt record with an executor
func (o *Prompt) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Prompts.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Prompt using the executor
func (o *Prompt) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Prompts.Query(
		sm.Where(Prompts.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after PromptSlice is retrieved from the database
func (o PromptSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Prompts.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Prompts.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Prompts.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Prompts.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o PromptSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("prompts", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o PromptSlice) copyMatchingRows(from ...*Prompt) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o PromptSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Prompts.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Prompt:
				o.copyMatchingRows(retrieved)
			case []*Prompt:
				o.copyMatchingRows(retrieved...)
			case PromptSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Prompt or a slice of Prompt
				// then run the AfterUpdateHooks on the slice
				_, err = Prompts.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o PromptSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Prompts.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Prompt:
				o.copyMatchingRows(retrieved)
			case []*Prompt:
				o.copyMatchingRows(retrieved...)
			case PromptSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Prompt or a slice of Prompt
				// then run the AfterDeleteHooks on the slice
				_, err = Prompts.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o PromptSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals PromptSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Prompts.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o PromptSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Prompts.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o PromptSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Prompts.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// PromptRunJobs starts a query for related objects on prompt_run_jobs
func (o *Prompt) PromptRunJobs(mods ...bob.Mod[*dialect.SelectQuery]) PromptRunJobsQuery {
	return PromptRunJobs.Query(append(mods,
		sm.Where(PromptRunJobs.Columns.PromptID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os PromptSlice) PromptRunJobs(mods ...bob.Mod[*dialect.SelectQuery]) PromptRunJobsQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return PromptRunJobs.Query(append(mods,
		sm.Where(psql.Group(PromptRunJobs.Columns.PromptID).OP("IN", PKArgExpr)),
	)...)
}

// User starts a query for related objects on users
func (o *Prompt) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os PromptSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[null.Val[int64]], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "bigint[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func insertPromptPromptRunJobs0(ctx context.Context, exec bob.Executor, promptRunJobs1 []*PromptRunJobSetter, prompt0 *Prompt) (PromptRunJobSlice, error) {
	for i := range promptRunJobs1 {
		promptRunJobs1[i].PromptID = omit.From(prompt0.ID)
	}

	ret, err := PromptRunJobs.Insert(bob.ToMods(promptRunJobs1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertPromptPromptRunJobs0: %w", err)
	}

	return ret, nil
}

func attachPromptPromptRunJobs0(ctx context.Context, exec bob.Executor, count int, promptRunJobs1 PromptRunJobSlice, prompt0 *Prompt) (PromptRunJobSlice, error) {
	setter := &PromptRunJobSetter{
		PromptID: omit.From(prompt0.ID),
	}

	err := promptRunJobs1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachPromptPromptRunJobs0: %w", err)
	}

	return promptRunJobs1, nil
}

func (prompt0 *Prompt) InsertPromptRunJobs(ctx context.Context, exec bob.Executor, related ...*PromptRunJobSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	promptRunJobs1, err := insertPromptPromptRunJobs0(ctx, exec, related, prompt0)
	if err != nil {
		return err
	}

	prompt0.R.PromptRunJobs = append(prompt0.R.PromptRunJobs, promptRunJobs1...)

	for _, rel := range promptRunJobs1 {
		rel.R.Prompt = prompt0
	}
	return nil
}

func (prompt0 *Prompt) AttachPromptRunJobs(ctx context.Context, exec bob.Executor, related ...*PromptRunJob) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	promptRunJobs1 := PromptRunJobSlice(related)

	_, err = attachPromptPromptRunJobs0(ctx, exec, len(related), promptRunJobs1, prompt0)
	if err != nil {
		return err
	}

	prompt0.R.PromptRunJobs = append(prompt0.R.PromptRunJobs, promptRunJobs1...)

	for _, rel := range related {
		rel.R.Prompt = prompt0
	}

	return nil
}

func attachPromptUser0(ctx context.Context, exec bob.Executor, count int, prompt0 *Prompt, user1 *User) (*Prompt, error) {
	setter := &PromptSetter{
		UserID: omitnull.From(user1.ID),
	}

	err := prompt0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachPromptUser0: %w", err)
	}

	return prompt0, nil
}

func (prompt0 *Prompt) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachPromptUser0(ctx, exec, 1, prompt0, user1)
	if err != nil {
		return err
	}

	prompt0.R.User = user1

	user1.R.Prompts = append(user1.R.Prompts, prompt0)

	return nil
}

func (prompt0 *Prompt) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachPromptUser0(ctx, exec, 1, prompt0, user1)
	if err != nil {
		return err
	}

	prompt0.R.User = user1

	user1.R.Prompts = append(user1.R.Prompts, prompt0)

	return nil
}

type promptWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, int64]
	UserID    psql.WhereNullMod[Q, int64]
	Name      psql.WhereMod[Q, string]
	Body      psql.WhereMod[Q, string]
	IsActive  psql.WhereMod[Q, bool]
	IsDefault psql.WhereMod[Q, bool]
	CreatedAt psql.WhereMod[Q, time.Time]
	UpdatedAt psql.WhereMod[Q, time.Time]
}

func (promptWhere[Q]) AliasedAs(alias string) promptWhere[Q] {
	return buildPromptWhere[Q](buildPromptColumns(alias))
}

func buildPromptWhere[Q psql.Filterable](cols promptColumns) promptWhere[Q] {
	return promptWhere[Q]{
		ID:        psql.Where[Q, int64](cols.ID),
		UserID:    psql.WhereNull[Q, int64](cols.UserID),
		Name:      psql.Where[Q, string](cols.Name),
		Body:      psql.Where[Q, string](cols.Body),
		IsActive:  psql.Where[Q, bool](cols.IsActive),
		IsDefault: psql.Where[Q, bool](cols.IsDefault),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt: psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Prompt) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "PromptRunJobs":
		rels, ok := retrieved.(PromptRunJobSlice)
		if !ok {
			return fmt.Errorf("prompt cannot load %T as %q", retrieved, name)
		}

		o.R.PromptRunJobs = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Prompt = o
			}
		}
		return nil
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("prompt cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.Prompts = PromptSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("prompt has no relationship %q", name)
	}
}

type promptPreloader struct {
	User func(...psql.PreloadOption) psql.Preloader
}

func buildPromptPreloader() promptPreloader {
	return promptPreloader{
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        Prompts,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type promptThenLoader[Q orm.Loadable] struct {
	PromptRunJobs func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	User          func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildPromptThenLoader[Q orm.Loadable]() promptThenLoader[Q] {
	type PromptRunJobsLoadInterface interface {
		LoadPromptRunJobs(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return promptThenLoader[Q]{
		PromptRunJobs: thenLoadBuilder[Q](
			"PromptRunJobs",
			func(ctx context.Context, exec bob.Executor, retrieved PromptRunJobsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadPromptRunJobs(ctx, exec, mods...)
			},
		),
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadPromptRunJobs loads the prompt's PromptRunJobs into the .R struct
func (o *Prompt) LoadPromptRunJobs(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.PromptRunJobs = nil

	related, err := o.PromptRunJobs(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Prompt = o
	}

	o.R.PromptRunJobs = related
	return nil
}

// LoadPromptRunJobs loads the prompt's PromptRunJobs into the .R struct
func (os PromptSlice) LoadPromptRunJobs(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	promptRunJobs, err := os.PromptRunJobs(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.PromptRunJobs = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range promptRunJobs {

			if !(o.ID == rel.PromptID) {
				continue
			}

			rel.R.Prompt = o

			o.R.PromptRunJobs = append(o.R.PromptRunJobs, rel)
		}
	}

	return nil
}

// LoadUser loads the prompt's User into the .R struct
func (o *Prompt) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Prompts = PromptSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the prompt's User into the .R struct
func (os PromptSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {
			if !o.UserID.IsValue() {
				continue
			}

			if !(o.UserID.IsValue() && o.UserID.MustGet() == rel.ID) {
				continue
			}

			rel.R.Prompts = append(rel.R.Prompts, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type promptJoins[Q dialect.Joinable] struct {
	typ           string
	PromptRunJobs modAs[Q, promptRunJobColumns]
	User          modAs[Q, userColumns]
}

func (j promptJoins[Q]) aliasedAs(alias string) promptJoins[Q] {
	return buildPromptJoins[Q](buildPromptColumns(alias), j.typ)
}

func buildPromptJoins[Q dialect.Joinable](cols promptColumns, typ string) promptJoins[Q] {
	return promptJoins[Q]{
		typ: typ,
		PromptRunJobs: modAs[Q, promptRunJobColumns]{
			c: PromptRunJobs.Columns,
			f: func(to promptRunJobColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, PromptRunJobs.Name().As(to.Alias())).On(
						to.PromptID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
