// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Transcription is an object representing the database table.
type Transcription struct {
	ID           int64                       `db:"id,pk" `
	UserID       int64                       `db:"user_id" `
	FullText     string                      `db:"full_text" `
	SegmentsJSON types.JSON[json.RawMessage] `db:"segments_json" `
	CreatedAt    time.Time                   `db:"created_at" `
	UpdatedAt    time.Time                   `db:"updated_at" `

	R transcriptionR `db:"-" `
}

// TranscriptionSlice is an alias for a slice of pointers to Transcription.
// This should almost always be used instead of []*Transcription.
type TranscriptionSlice []*Transcription

// Transcriptions contains methods to work with the transcriptions table
var Transcriptions = psql.NewTablex[*Transcription, TranscriptionSlice, *TranscriptionSetter]("", "transcriptions", buildTranscriptionColumns("transcriptions"))

// TranscriptionsQuery is a query on the transcriptions table
type TranscriptionsQuery = *psql.ViewQuery[*Transcription, TranscriptionSlice]

// transcriptionR is where relationships are stored.
type transcriptionR struct {
	User *User // transcriptions.transcriptions_user_id_fkey
}

func buildTranscriptionColumns(alias string) transcriptionColumns {
	return transcriptionColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "full_text", "segments_json", "created_at", "updated_at",
		).WithParent("transcriptions"),
		tableAlias:   alias,
		ID:           psql.Quote(alias, "id"),
		UserID:       psql.Quote(alias, "user_id"),
		FullText:     psql.Quote(alias, "full_text"),
		SegmentsJSON: psql.Quote(alias, "segments_json"),
		CreatedAt:    psql.Quote(alias, "created_at"),
		UpdatedAt:    psql.Quote(alias, "updated_at"),
	}
}

type transcriptionColumns struct {
	expr.ColumnsExpr
	tableAlias   string
	ID           psql.Expression
	UserID       psql.Expression
	FullText     psql.Expression
	SegmentsJSON psql.Expression
	CreatedAt    psql.Expression
	UpdatedAt    psql.Expression
}

func (c transcriptionColumns) Alias() string {
	return c.tableAlias
}

func (transcriptionColumns) AliasedAs(alias string) transcriptionColumns {
	return buildTranscriptionColumns(alias)
}

// TranscriptionSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type TranscriptionSetter struct {
	ID           omit.Val[int64]                       `db:"id,pk" `
	UserID       omit.Val[int64]                       `db:"user_id" `
	FullText     omit.Val[string]                      `db:"full_text" `
	SegmentsJSON omit.Val[types.JSON[json.RawMessage]] `db:"segments_json" `
	CreatedAt    omit.Val[time.Time]                   `db:"created_at" `
	UpdatedAt    omit.Val[time.Time]                   `db:"updated_at" `
}

func (s TranscriptionSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.FullText.IsValue() {
		vals = append(vals, "full_text")
	}
	if s.SegmentsJSON.IsValue() {
		vals = append(vals, "segments_json")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s TranscriptionSetter) Overwrite(t *Transcription) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.FullText.IsValue() {
		t.FullText = s.FullText.MustGet()
	}
	if s.SegmentsJSON.IsValue() {
		t.SegmentsJSON = s.SegmentsJSON.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *TranscriptionSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Transcriptions.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 6)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[1] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.FullText.IsValue() {
			vals[2] = psql.Arg(s.FullText.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.SegmentsJSON.IsValue() {
			vals[3] = psql.Arg(s.SegmentsJSON.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[4] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[5] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s TranscriptionSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s TranscriptionSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.FullText.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "full_text")...),
			psql.Arg(s.FullText),
		}})
	}

	if s.SegmentsJSON.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "segments_json")...),
			psql.Arg(s.SegmentsJSON),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindTranscription retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindTranscription(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Transcription, error) {
	if len(cols) == 0 {
		return Transcriptions.Query(
			sm.Where(Transcriptions.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Transcriptions.Query(
		sm.Where(Transcriptions.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Transcriptions.Columns.Only(cols...)),
	).One(ctx, exec)
}

// TranscriptionExists checks the presence of a single record by primary key
func TranscriptionExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Transcriptions.Query(
		sm.Where(Transcriptions.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Transcription is retrieved from the database
func (o *Transcription) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Transcriptions.AfterSelectHooks.RunHooks(ctx, exec, TranscriptionSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Transcriptions.AfterInsertHooks.RunHooks(ctx, exec, TranscriptionSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Transcriptions.AfterUpdateHooks.RunHooks(ctx, exec, TranscriptionSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Transcriptions.AfterDeleteHooks.RunHooks(ctx, exec, TranscriptionSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Transcription
func (o *Transcription) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Transcription) pkEQ() dialect.Expression {
	return psql.Quote("transcriptions", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Transcription
func (o *Transcription) Update(ctx context.Context, exec bob.Executor, s *TranscriptionSetter) error {
	v, err := Transcriptions.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Transcription record with an executor
func (o *Transcription) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Transcriptions.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Transcription using the executor
func (o *Transcription) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Transcriptions.Query(
		sm.Where(Transcriptions.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after TranscriptionSlice is retrieved from the database
func (o TranscriptionSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Transcriptions.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Transcriptions.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Transcriptions.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Transcriptions.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o TranscriptionSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("transcriptions", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o TranscriptionSlice) copyMatchingRows(from ...*Transcription) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o TranscriptionSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Transcriptions.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Transcription:
				o.copyMatchingRows(retrieved)
			case []*Transcription:
				o.copyMatchingRows(retrieved...)
			case TranscriptionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Transcription or a slice of Transcription
				// then run the AfterUpdateHooks on the slice
				_, err = Transcriptions.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o TranscriptionSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Transcriptions.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Transcription:
				o.copyMatchingRows(retrieved)
			case []*Transcription:
				o.copyMatchingRows(retrieved...)
			case TranscriptionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Transcription or a slice of Transcription
				// then run the AfterDeleteHooks on the slice
				_, err = Transcriptions.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o TranscriptionSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals TranscriptionSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Transcriptions.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o TranscriptionSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Transcriptions.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o TranscriptionSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Transcriptions.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// User starts a query for related objects on users
func (o *Transcription) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os TranscriptionSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "bigint[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachTranscriptionUser0(ctx context.Context, exec bob.Executor, count int, transcription0 *Transcription, user1 *User) (*Transcription, error) {
	setter := &TranscriptionSetter{
		UserID: omit.From(user1.ID),
	}

	err := transcription0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachTranscriptionUser0: %w", err)
	}

	return transcription0, nil
}

func (transcription0 *Transcription) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachTranscriptionUser0(ctx, exec, 1, transcription0, user1)
	if err != nil {
		return err
	}

	transcription0.R.User = user1

	user1.R.Transcriptions = append(user1.R.Transcriptions, transcription0)

	return nil
}

func (transcription0 *Transcription) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachTranscriptionUser0(ctx, exec, 1, transcription0, user1)
	if err != nil {
		return err
	}

	transcription0.R.User = user1

	user1.R.Transcriptions = append(user1.R.Transcriptions, transcription0)

	return nil
}

type transcriptionWhere[Q psql.Filterable] struct {
	ID           psql.WhereMod[Q, int64]
	UserID       psql.WhereMod[Q, int64]
	FullText     psql.WhereMod[Q, string]
	SegmentsJSON psql.WhereMod[Q, types.JSON[json.RawMessage]]
	CreatedAt    psql.WhereMod[Q, time.Time]
	UpdatedAt    psql.WhereMod[Q, time.Time]
}

func (transcriptionWhere[Q]) AliasedAs(alias string) transcriptionWhere[Q] {
	return buildTranscriptionWhere[Q](buildTranscriptionColumns(alias))
}

func buildTranscriptionWhere[Q psql.Filterable](cols transcriptionColumns) transcriptionWhere[Q] {
	return transcriptionWhere[Q]{
		ID:           psql.Where[Q, int64](cols.ID),
		UserID:       psql.Where[Q, int64](cols.UserID),
		FullText:     psql.Where[Q, string](cols.FullText),
		SegmentsJSON: psql.Where[Q, types.JSON[json.RawMessage]](cols.SegmentsJSON),
		CreatedAt:    psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:    psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Transcription) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("transcription cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.Transcriptions = TranscriptionSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("transcription has no relationship %q", name)
	}
}

type transcriptionPreloader struct {
	User func(...psql.PreloadOption) psql.Preloader
}

func buildTranscriptionPreloader() transcriptionPreloader {
	return transcriptionPreloader{
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        Transcriptions,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type transcriptionThenLoader[Q orm.Loadable] struct {
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildTranscriptionThenLoader[Q orm.Loadable]() transcriptionThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return transcriptionThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the transcription's User into the .R struct
func (o *Transcription) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Transcriptions = TranscriptionSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the transcription's User into the .R struct
func (os TranscriptionSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.Transcriptions = append(rel.R.Transcriptions, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type transcriptionJoins[Q dialect.Joinable] struct {
	typ  string
	User modAs[Q, userColumns]
}

func (j transcriptionJoins[Q]) aliasedAs(alias string) transcriptionJoins[Q] {
	return buildTranscriptionJoins[Q](buildTranscriptionColumns(alias), j.typ)
}

func buildTranscriptionJoins[Q dialect.Joinable](cols transcriptionColumns, typ string) transcriptionJoins[Q] {
	return transcriptionJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
