// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// User is an object representing the database table.
type User struct {
	ID           int64            `db:"id,pk" `
	AuthProvider string           `db:"auth_provider" `
	AuthSubject  string           `db:"auth_subject" `
	Email        null.Val[string] `db:"email" `
	Name         null.Val[string] `db:"name" `
	CreatedAt    time.Time        `db:"created_at" `
	UpdatedAt    time.Time        `db:"updated_at" `

	R userR `db:"-" `
}

// UserSlice is an alias for a slice of pointers to User.
// This should almost always be used instead of []*User.
type UserSlice []*User

// Users contains methods to work with the users table
var Users = psql.NewTablex[*User, UserSlice, *UserSetter]("", "users", buildUserColumns("users"))

// UsersQuery is a query on the users table
type UsersQuery = *psql.ViewQuery[*User, UserSlice]

// userR is where relationships are stored.
type userR struct {
	Articles       ArticleSlice       // articles.articles_user_id_fkey
	ExternalTokens ExternalTokenSlice // external_tokens.external_tokens_user_id_fkey
	Prompts        PromptSlice        // prompts.prompts_user_id_fkey
	Transcriptions TranscriptionSlice // transcriptions.transcriptions_user_id_fkey
}

func buildUserColumns(alias string) userColumns {
	return userColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "auth_provider", "auth_subject", "email", "name", "created_at", "updated_at",
		).WithParent("users"),
		tableAlias:   alias,
		ID:           psql.Quote(alias, "id"),
		AuthProvider: psql.Quote(alias, "auth_provider"),
		AuthSubject:  psql.Quote(alias, "auth_subject"),
		Email:        psql.Quote(alias, "email"),
		Name:         psql.Quote(alias, "name"),
		CreatedAt:    psql.Quote(alias, "created_at"),
		UpdatedAt:    psql.Quote(alias, "updated_at"),
	}
}

type userColumns struct {
	expr.ColumnsExpr
	tableAlias   string
	ID           psql.Expression
	AuthProvider psql.Expression
	AuthSubject  psql.Expression
	Email        psql.Expression
	Name         psql.Expression
	CreatedAt    psql.Expression
	UpdatedAt    psql.Expression
}

func (c userColumns) Alias() string {
	return c.tableAlias
}

func (userColumns) AliasedAs(alias string) userColumns {
	return buildUserColumns(alias)
}

// UserSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserSetter struct {
	ID           omit.Val[int64]      `db:"id,pk" `
	AuthProvider omit.Val[string]     `db:"auth_provider" `
	AuthSubject  omit.Val[string]     `db:"auth_subject" `
	Email        omitnull.Val[string] `db:"email" `
	Name         omitnull.Val[string] `db:"name" `
	CreatedAt    omit.Val[time.Time]  `db:"created_at" `
	UpdatedAt    omit.Val[time.Time]  `db:"updated_at" `
}

func (s UserSetter) SetColumns() []string {
	vals := make([]string, 0, 7)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.AuthProvider.IsValue() {
		vals = append(vals, "auth_provider")
	}
	if s.AuthSubject.IsValue() {
		vals = append(vals, "auth_subject")
	}
	if !s.Email.IsUnset() {
		vals = append(vals, "email")
	}
	if !s.Name.IsUnset() {
		vals = append(vals, "name")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s UserSetter) Overwrite(t *User) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.AuthProvider.IsValue() {
		t.AuthProvider = s.AuthProvider.MustGet()
	}
	if s.AuthSubject.IsValue() {
		t.AuthSubject = s.AuthSubject.MustGet()
	}
	if !s.Email.IsUnset() {
		t.Email = s.Email.MustGetNull()
	}
	if !s.Name.IsUnset() {
		t.Name = s.Name.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *UserSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Users.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 7)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.AuthProvider.IsValue() {
			vals[1] = psql.Arg(s.AuthProvider.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.AuthSubject.IsValue() {
			vals[2] = psql.Arg(s.AuthSubject.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if !s.Email.IsUnset() {
			vals[3] = psql.Arg(s.Email.MustGetNull())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.Name.IsUnset() {
			vals[4] = psql.Arg(s.Name.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[5] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[6] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s UserSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s UserSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 7)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.AuthProvider.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "auth_provider")...),
			psql.Arg(s.AuthProvider),
		}})
	}

	if s.AuthSubject.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "auth_subject")...),
			psql.Arg(s.AuthSubject),
		}})
	}

	if !s.Email.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "email")...),
			psql.Arg(s.Email),
		}})
	}

	if !s.Name.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindUser retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUser(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*User, error) {
	if len(cols) == 0 {
		return Users.Query(
			sm.Where(Users.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Users.Query(
		sm.Where(Users.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Users.Columns.Only(cols...)),
	).One(ctx, exec)
}

// UserExists checks the presence of a single record by primary key
func UserExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Users.Query(
		sm.Where(Users.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after User is retrieved from the database
func (o *User) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, UserSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the User
func (o *User) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *User) pkEQ() dialect.Expression {
	return psql.Quote("users", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the User
func (o *User) Update(ctx context.Context, exec bob.Executor, s *UserSetter) error {
	v, err := Users.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single User record with an executor
func (o *User) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Users.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the User using the executor
func (o *User) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Users.Query(
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after UserSlice is retrieved from the database
func (o UserSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o UserSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("users", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o UserSlice) copyMatchingRows(from ...*User) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o UserSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterUpdateHooks on the slice
				_, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o UserSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterDeleteHooks on the slice
				_, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o UserSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o UserSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o UserSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Users.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Articles starts a query for related objects on articles
func (o *User) Articles(mods ...bob.Mod[*dialect.SelectQuery]) ArticlesQuery {
	return Articles.Query(append(mods,
		sm.Where(Articles.Columns.UserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) Articles(mods ...bob.Mod[*dialect.SelectQuery]) ArticlesQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return Articles.Query(append(mods,
		sm.Where(psql.Group(Articles.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

// ExternalTokens starts a query for related objects on external_tokens
func (o *User) ExternalTokens(mods ...bob.Mod[*dialect.SelectQuery]) ExternalTokensQuery {
	return ExternalTokens.Query(append(mods,
		sm.Where(ExternalTokens.Columns.UserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) ExternalTokens(mods ...bob.Mod[*dialect.SelectQuery]) ExternalTokensQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return ExternalTokens.Query(append(mods,
		sm.Where(psql.Group(ExternalTokens.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

// Prompts starts a query for related objects on prompts
func (o *User) Prompts(mods ...bob.Mod[*dialect.SelectQuery]) PromptsQuery {
	return Prompts.Query(append(mods,
		sm.Where(Prompts.Columns.UserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) Prompts(mods ...bob.Mod[*dialect.SelectQuery]) PromptsQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return Prompts.Query(append(mods,
		sm.Where(psql.Group(Prompts.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

// Transcriptions starts a query for related objects on transcriptions
func (o *User) Transcriptions(mods ...bob.Mod[*dialect.SelectQuery]) TranscriptionsQuery {
	return Transcriptions.Query(append(mods,
		sm.Where(Transcriptions.Columns.UserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) Transcriptions(mods ...bob.Mod[*dialect.SelectQuery]) TranscriptionsQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return Transcriptions.Query(append(mods,
		sm.Where(psql.Group(Transcriptions.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

func insertUserArticles0(ctx context.Context, exec bob.Executor, articles1 []*ArticleSetter, user0 *User) (ArticleSlice, error) {
	for i := range articles1 {
		articles1[i].UserID = omit.From(user0.ID)
	}

	ret, err := Articles.Insert(bob.ToMods(articles1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserArticles0: %w", err)
	}

	return ret, nil
}

func attachUserArticles0(ctx context.Context, exec bob.Executor, count int, articles1 ArticleSlice, user0 *User) (ArticleSlice, error) {
	setter := &ArticleSetter{
		UserID: omit.From(user0.ID),
	}

	err := articles1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserArticles0: %w", err)
	}

	return articles1, nil
}

func (user0 *User) InsertArticles(ctx context.Context, exec bob.Executor, related ...*ArticleSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	articles1, err := insertUserArticles0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.Articles = append(user0.R.Articles, articles1...)

	for _, rel := range articles1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachArticles(ctx context.Context, exec bob.Executor, related ...*Article) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	articles1 := ArticleSlice(related)

	_, err = attachUserArticles0(ctx, exec, len(related), articles1, user0)
	if err != nil {
		return err
	}

	user0.R.Articles = append(user0.R.Articles, articles1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

func insertUserExternalTokens0(ctx context.Context, exec bob.Executor, externalTokens1 []*ExternalTokenSetter, user0 *User) (ExternalTokenSlice, error) {
	for i := range externalTokens1 {
		externalTokens1[i].UserID = omit.From(user0.ID)
	}

	ret, err := ExternalTokens.Insert(bob.ToMods(externalTokens1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserExternalTokens0: %w", err)
	}

	return ret, nil
}

func attachUserExternalTokens0(ctx context.Context, exec bob.Executor, count int, externalTokens1 ExternalTokenSlice, user0 *User) (ExternalTokenSlice, error) {
	setter := &ExternalTokenSetter{
		UserID: omit.From(user0.ID),
	}

	err := externalTokens1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserExternalTokens0: %w", err)
	}

	return externalTokens1, nil
}

func (user0 *User) InsertExternalTokens(ctx context.Context, exec bob.Executor, related ...*ExternalTokenSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	externalTokens1, err := insertUserExternalTokens0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.ExternalTokens = append(user0.R.ExternalTokens, externalTokens1...)

	for _, rel := range externalTokens1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachExternalTokens(ctx context.Context, exec bob.Executor, related ...*ExternalToken) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	externalTokens1 := ExternalTokenSlice(related)

	_, err = attachUserExternalTokens0(ctx, exec, len(related), externalTokens1, user0)
	if err != nil {
		return err
	}

	user0.R.ExternalTokens = append(user0.R.ExternalTokens, externalTokens1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

func insertUserPrompts0(ctx context.Context, exec bob.Executor, prompts1 []*PromptSetter, user0 *User) (PromptSlice, error) {
	for i := range prompts1 {
		prompts1[i].UserID = omitnull.From(user0.ID)
	}

	ret, err := Prompts.Insert(bob.ToMods(prompts1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserPrompts0: %w", err)
	}

	return ret, nil
}

func attachUserPrompts0(ctx context.Context, exec bob.Executor, count int, prompts1 PromptSlice, user0 *User) (PromptSlice, error) {
	setter := &PromptSetter{
		UserID: omitnull.From(user0.ID),
	}

	err := prompts1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserPrompts0: %w", err)
	}

	return prompts1, nil
}

func (user0 *User) InsertPrompts(ctx context.Context, exec bob.Executor, related ...*PromptSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	prompts1, err := insertUserPrompts0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.Prompts = append(user0.R.Prompts, prompts1...)

	for _, rel := range prompts1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachPrompts(ctx context.Context, exec bob.Executor, related ...*Prompt) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	prompts1 := PromptSlice(related)

	_, err = attachUserPrompts0(ctx, exec, len(related), prompts1, user0)
	if err != nil {
		return err
	}

	user0.R.Prompts = append(user0.R.Prompts, prompts1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

func insertUserTranscriptions0(ctx context.Context, exec bob.Executor, transcriptions1 []*TranscriptionSetter, user0 *User) (TranscriptionSlice, error) {
	for i := range transcriptions1 {
		transcriptions1[i].UserID = omit.From(user0.ID)
	}

	ret, err := Transcriptions.Insert(bob.ToMods(transcriptions1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserTranscriptions0: %w", err)
	}

	return ret, nil
}

func attachUserTranscriptions0(ctx context.Context, exec bob.Executor, count int, transcriptions1 TranscriptionSlice, user0 *User) (TranscriptionSlice, error) {
	setter := &TranscriptionSetter{
		UserID: omit.From(user0.ID),
	}

	err := transcriptions1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserTranscriptions0: %w", err)
	}

	return transcriptions1, nil
}

func (user0 *User) InsertTranscriptions(ctx context.Context, exec bob.Executor, related ...*TranscriptionSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	transcriptions1, err := insertUserTranscriptions0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.Transcriptions = append(user0.R.Transcriptions, transcriptions1...)

	for _, rel := range transcriptions1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachTranscriptions(ctx context.Context, exec bob.Executor, related ...*Transcription) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	transcriptions1 := TranscriptionSlice(related)

	_, err = attachUserTranscriptions0(ctx, exec, len(related), transcriptions1, user0)
	if err != nil {
		return err
	}

	user0.R.Transcriptions = append(user0.R.Transcriptions, transcriptions1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

type userWhere[Q psql.Filterable] struct {
	ID           psql.WhereMod[Q, int64]
	AuthProvider psql.WhereMod[Q, string]
	AuthSubject  psql.WhereMod[Q, string]
	Email        psql.WhereNullMod[Q, string]
	Name         psql.WhereNullMod[Q, string]
	CreatedAt    psql.WhereMod[Q, time.Time]
	UpdatedAt    psql.WhereMod[Q, time.Time]
}

func (userWhere[Q]) AliasedAs(alias string) userWhere[Q] {
	return buildUserWhere[Q](buildUserColumns(alias))
}

func buildUserWhere[Q psql.Filterable](cols userColumns) userWhere[Q] {
	return userWhere[Q]{
		ID:           psql.Where[Q, int64](cols.ID),
		AuthProvider: psql.Where[Q, string](cols.AuthProvider),
		AuthSubject:  psql.Where[Q, string](cols.AuthSubject),
		Email:        psql.WhereNull[Q, string](cols.Email),
		Name:         psql.WhereNull[Q, string](cols.Name),
		CreatedAt:    psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:    psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *User) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Articles":
		rels, ok := retrieved.(ArticleSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.Articles = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	case "ExternalTokens":
		rels, ok := retrieved.(ExternalTokenSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.ExternalTokens = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	case "Prompts":
		rels, ok := retrieved.(PromptSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.Prompts = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	case "Transcriptions":
		rels, ok := retrieved.(TranscriptionSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.Transcriptions = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	default:
		return fmt.Errorf("user has no relationship %q", name)
	}
}

type userPreloader struct{}

func buildUserPreloader() userPreloader {
	return userPreloader{}
}

type userThenLoader[Q orm.Loadable] struct {
	Articles       func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	ExternalTokens func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Prompts        func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Transcriptions func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUserThenLoader[Q orm.Loadable]() userThenLoader[Q] {
	type ArticlesLoadInterface interface {
		LoadArticles(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ExternalTokensLoadInterface interface {
		LoadExternalTokens(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type PromptsLoadInterface interface {
		LoadPrompts(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TranscriptionsLoadInterface interface {
		LoadTranscriptions(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return userThenLoader[Q]{
		Articles: thenLoadBuilder[Q](
			"Articles",
			func(ctx context.Context, exec bob.Executor, retrieved ArticlesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadArticles(ctx, exec, mods...)
			},
		),
		ExternalTokens: thenLoadBuilder[Q](
			"ExternalTokens",
			func(ctx context.Context, exec bob.Executor, retrieved ExternalTokensLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadExternalTokens(ctx, exec, mods...)
			},
		),
		Prompts: thenLoadBuilder[Q](
			"Prompts",
			func(ctx context.Context, exec bob.Executor, retrieved PromptsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadPrompts(ctx, exec, mods...)
			},
		),
		Transcriptions: thenLoadBuilder[Q](
			"Transcriptions",
			func(ctx context.Context, exec bob.Executor, retrieved TranscriptionsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTranscriptions(ctx, exec, mods...)
			},
		),
	}
}

// LoadArticles loads the user's Articles into the .R struct
func (o *User) LoadArticles(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Articles = nil

	related, err := o.Articles(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.Articles = related
	return nil
}

// LoadArticles loads the user's Articles into the .R struct
func (os UserSlice) LoadArticles(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	articles, err := os.Articles(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Articles = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range articles {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.Articles = append(o.R.Articles, rel)
		}
	}

	return nil
}

// LoadExternalTokens loads the user's ExternalTokens into the .R struct
func (o *User) LoadExternalTokens(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.ExternalTokens = nil

	related, err := o.ExternalTokens(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.ExternalTokens = related
	return nil
}

// LoadExternalTokens loads the user's ExternalTokens into the .R struct
func (os UserSlice) LoadExternalTokens(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	externalTokens, err := os.ExternalTokens(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.ExternalTokens = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range externalTokens {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.ExternalTokens = append(o.R.ExternalTokens, rel)
		}
	}

	return nil
}

// LoadPrompts loads the user's Prompts into the .R struct
func (o *User) LoadPrompts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Prompts = nil

	related, err := o.Prompts(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.Prompts = related
	return nil
}

// LoadPrompts loads the user's Prompts into the .R struct
func (os UserSlice) LoadPrompts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	prompts, err := os.Prompts(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Prompts = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range prompts {

			if !rel.UserID.IsValue() {
				continue
			}
			if !(rel.UserID.IsValue() && o.ID == rel.UserID.MustGet()) {
				continue
			}

			rel.R.User = o

			o.R.Prompts = append(o.R.Prompts, rel)
		}
	}

	return nil
}

// LoadTranscriptions loads the user's Transcriptions into the .R struct
func (o *User) LoadTranscriptions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Transcriptions = nil

	related, err := o.Transcriptions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.Transcriptions = related
	return nil
}

// LoadTranscriptions loads the user's Transcriptions into the .R struct
func (os UserSlice) LoadTranscriptions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	transcriptions, err := os.Transcriptions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Transcriptions = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range transcriptions {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.Transcriptions = append(o.R.Transcriptions, rel)
		}
	}

	return nil
}

type userJoins[Q dialect.Joinable] struct {
	typ            string
	Articles       modAs[Q, articleColumns]
	ExternalTokens modAs[Q, externalTokenColumns]
	Prompts        modAs[Q, promptColumns]
	Transcriptions modAs[Q, transcriptionColumns]
}

func (j userJoins[Q]) aliasedAs(alias string) userJoins[Q] {
	return buildUserJoins[Q](buildUserColumns(alias), j.typ)
}

func buildUserJoins[Q dialect.Joinable](cols userColumns, typ string) userJoins[Q] {
	return userJoins[Q]{
		typ: typ,
		Articles: modAs[Q, articleColumns]{
			c: Articles.Columns,
			f: func(to articleColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Articles.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		ExternalTokens: modAs[Q, externalTokenColumns]{
			c: ExternalTokens.Columns,
			f: func(to externalTokenColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, ExternalTokens.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Prompts: modAs[Q, promptColumns]{
			c: Prompts.Columns,
			f: func(to promptColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Prompts.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Transcriptions: modAs[Q, transcriptionColumns]{
			c: Transcriptions.Columns,
			f: func(to transcriptionColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Transcriptions.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
